/**
 * Localized sample data for all 16 supported locales.
 * Folder names, prompt titles/texts, conversation titles, and UI labels
 * are all translated. Defaults fall back to English where omitted.
 */

const NOW = Date.now();
const DAY = 86400000;

function make(locale) {
  const {
    title, folderLabel, promptLabel,
    folderScreenTitle = 'Keep your conversations organized',
    promptScreenTitle = 'Your best prompts, always at hand',
    mobileScreenTitle = 'Access your Gemini chats from your phone',
    contextMenuScreenTitle = 'Save a conversation in one right-click',
    ctxMenuSaveLabel = 'Save to Gemini Folders',
    ctxBack    = 'Back',
    ctxForward = 'Forward',
    ctxSavePage = 'Save page as…',
    ctxPrint   = 'Print…',
    geminiNewChat            = "New chat",
    geminiMyContent          = "My library",
    geminiDiscussions        = "Discussions",
    geminiSettings           = "Settings & help",
    geminiShowReasoning      = "Show thinking",
    geminiInputPlaceholder   = "Ask Gemini",
    geminiTools              = "Tools",
    geminiAiReply            = "Here’s a clean refactored version using async/await and proper error handling…",
    syncFolderName = 'Gemini Folders (Sync)',
    research, writing, travel,
    dev          = 'Dev',
    // Conversation titles (English defaults)
    devChat1     = 'Refactor Node.js API',
    devChat2     = 'Debug React hook',
    devChat3     = 'Write unit tests',
    resChat1     = 'Market analysis 2025',
    resChat2     = 'Competitor overview',
    writeChat1   = 'Blog post — AI productivity',
    writeChat2   = 'Newsletter draft',
    travelChat1  = 'Japan trip itinerary',
    // Prompt titles/texts
    codeReviewer, codeReviewerText,
    emailPro,     emailProText,
    explainSimply, blogOutline,
    debugHelper     = 'Debug Helper',
    debugHelperText = 'I have the following error or unexpected behavior. Help me diagnose the root cause step by step, then suggest a fix.',
  } = locale;

  return {
    title,
    folderLabel,
    promptLabel,
    folderScreenTitle,
    promptScreenTitle,
    mobileScreenTitle,
    contextMenuScreenTitle,
    ctxMenuSaveLabel,
    ctxBack,
    ctxForward,
    ctxSavePage,
    ctxPrint,
    geminiNewChat,
    geminiMyContent,
    geminiDiscussions,
    geminiSettings,
    geminiShowReasoning,
    geminiInputPlaceholder,
    geminiTools,
    geminiAiReply,
    syncFolderName,
    devChat1,
    devChat2,
    resChat1,
    writeChat1,
    pinnedFolders: [`💻 ${dev}`],
    folders: {
      [`💻 ${dev}`]: [
        { url: 'https://gemini.google.com/app/aaa1', title: devChat1,    timestamp: NOW - 1 * DAY },
        { url: 'https://gemini.google.com/app/aaa2', title: devChat2,    timestamp: NOW - 2 * DAY },
        { url: 'https://gemini.google.com/app/aaa3', title: devChat3,    timestamp: NOW - 3 * DAY },
      ],
      [`📊 ${research}`]: [
        { url: 'https://gemini.google.com/app/bbb1', title: resChat1,    timestamp: NOW - 4 * DAY },
        { url: 'https://gemini.google.com/app/bbb2', title: resChat2,    timestamp: NOW - 5 * DAY },
      ],
      [`✍️ ${writing}`]: [
        { url: 'https://gemini.google.com/app/ccc1', title: writeChat1,  timestamp: NOW - 6 * DAY },
        { url: 'https://gemini.google.com/app/ccc2', title: writeChat2,  timestamp: NOW - 7 * DAY },
      ],
      [`🌍 ${travel}`]: [
        { url: 'https://gemini.google.com/app/ddd1', title: travelChat1, timestamp: NOW - 8 * DAY },
      ],
    },
    prompts: {
      [codeReviewer]: {
        text: codeReviewerText,
        timestamp: NOW - 1 * DAY,
        pinned: true,
      },
      [emailPro]: {
        text: emailProText,
        timestamp: NOW - 2 * DAY,
        pinned: true,
      },
      [explainSimply]: {
        text: 'Explain the following concept as if I were 12 years old, using simple words and a concrete real-world analogy.',
        timestamp: NOW - 3 * DAY,
      },
      [blogOutline]: {
        text: 'Create a structured outline for a blog post about the following topic: introduction, 5 main sections with key points, and a conclusion.',
        timestamp: NOW - 4 * DAY,
      },
      [debugHelper]: {
        text: debugHelperText,
        timestamp: NOW - 5 * DAY,
      },
    },
  };
}

// ─── Locale definitions ───────────────────────────────────────────────────────

module.exports = {

  en: make({
    title:            'Organize your Gemini conversations',
    folderLabel:      '📁 Folder Mode',
    promptLabel:      '📝 Prompt Mode',
    folderScreenTitle: 'Keep your conversations organized',
    promptScreenTitle: 'Your best prompts, always at hand',
    mobileScreenTitle: 'Access your Gemini chats from your phone',
    contextMenuScreenTitle: 'Save a conversation in one right-click',
    ctxMenuSaveLabel: 'Save to Gemini Folders',
    ctxBack:    'Back',
    ctxForward: 'Forward',
    ctxSavePage: 'Save page as…',
    ctxPrint:   'Print…',
    geminiNewChat:           'New chat',
    geminiMyContent:         'My library',
    geminiDiscussions:       'Discussions',
    geminiSettings:          'Settings & help',
    geminiShowReasoning:     'Show thinking',
    geminiInputPlaceholder:  'Ask Gemini',
    geminiTools:             'Tools',
    geminiAiReply:           "Here's a clean refactored version using async/await and proper error handling…",
    syncFolderName: 'Gemini Folders (Sync)',
    research:         'Research',
    writing:          'Writing',
    travel:           'Travel',
    codeReviewer:     'Code Reviewer',
    codeReviewerText: 'Review the following code for bugs, security issues, and best practices. Suggest concrete improvements with explanations.',
    emailPro:         'Email Pro',
    emailProText:     'Write a professional email for the following context. Be concise, clear, and use a polite tone. Sign off with my name.',
    explainSimply:    'Explain Simply',
    blogOutline:      'Blog Outline',
  }),

  fr: make({
    title:            'Organisez vos conversations Gemini',
    folderLabel:      '📁 Mode Dossiers',
    promptLabel:      '📝 Mode Prompts',
    folderScreenTitle: 'Gardez vos conversations organisées',
    promptScreenTitle: 'Vos meilleurs prompts, toujours à portée',
    mobileScreenTitle: 'Accédez à vos chats Gemini depuis votre téléphone',
    contextMenuScreenTitle: 'Sauvegardez une conversation en un clic droit',
    ctxMenuSaveLabel: 'Sauvegarder dans Dossiers Gemini',
    ctxBack:    'Retour',
    ctxForward: 'Suivant',
    ctxSavePage: 'Enregistrer sous…',
    ctxPrint:   'Imprimer…',
    geminiNewChat:           'Nouvelle discussion',
    geminiMyContent:         'Mes contenus',
    geminiDiscussions:       'Discussions',
    geminiSettings:          'Paramètres et aide',
    geminiShowReasoning:     'Afficher le raisonnement',
    geminiInputPlaceholder:  'Saisissez un prompt pour Gemini',
    geminiTools:             'Outils',
    geminiAiReply:           'Voici une version refactorisée propre avec async/await et une gestion des erreurs…',
    syncFolderName: 'Dossiers Gemini (Sync)',
    research:         'Recherche',
    writing:          'Rédaction',
    travel:           'Voyages',
    dev:              'Code',
    devChat1:         'Refactoriser l\'API Node.js',
    devChat2:         'Déboguer un hook React',
    devChat3:         'Écrire des tests unitaires',
    resChat1:         'Analyse de marché 2025',
    resChat2:         'Panorama de la concurrence',
    writeChat1:       'Article de blog — IA',
    writeChat2:       'Brouillon de newsletter',
    travelChat1:      'Itinéraire Japon',
    codeReviewer:     'Revue de code',
    codeReviewerText: 'Analyse ce code pour détecter les bugs, les problèmes de sécurité et les mauvaises pratiques. Propose des améliorations concrètes avec explications.',
    emailPro:         'Email Pro',
    emailProText:     'Rédige un e-mail professionnel pour le contexte suivant. Sois concis, clair et adopte un ton poli. Signe avec mon prénom.',
    explainSimply:    'Expliquer simplement',
    blogOutline:      'Plan de blog',
    debugHelper:      'Débogueur',
    debugHelperText:  'Voici mon erreur ou comportement inattendu. Aide-moi à diagnostiquer la cause profonde étape par étape, puis suggère une solution.',
  }),

  de: make({
    title:            'Gemini-Gespräche organisieren',
    folderLabel:      '📁 Ordner-Modus',
    promptLabel:      '📝 Prompt-Modus',
    folderScreenTitle: 'Gespräche einfach organisieren',
    promptScreenTitle: 'Ihre besten Prompts, stets griffbereit',
    mobileScreenTitle: 'Gemini-Chats auch auf dem Handy',
    contextMenuScreenTitle: 'Gespräch per Rechtsklick speichern',
    ctxMenuSaveLabel: 'In Gemini-Ordner speichern',
    ctxBack:    'Zurück',
    ctxForward: 'Vor',
    ctxSavePage: 'Seite speichern unter…',
    ctxPrint:   'Drucken…',
    geminiNewChat:           'Neuer Chat',
    geminiMyContent:         'Meine Inhalte',
    geminiDiscussions:       'Diskussionen',
    geminiSettings:          'Einstellungen & Hilfe',
    geminiShowReasoning:     'Überlegung anzeigen',
    geminiInputPlaceholder:  'Gemini fragen',
    geminiTools:             'Werkzeuge',
    geminiAiReply:           'Hier ist eine saubere Refaktorierung mit async/await und ordentlicher Fehlerbehandlung…',
    syncFolderName: 'Gemini-Ordner (Sync)',
    research:         'Recherche',
    writing:          'Schreiben',
    travel:           'Reisen',
    dev:              'Code',
    devChat1:         'Node.js API refaktorieren',
    devChat2:         'React Hook debuggen',
    devChat3:         'Unit-Tests schreiben',
    resChat1:         'Marktanalyse 2025',
    resChat2:         'Wettbewerber-Übersicht',
    writeChat1:       'Blogbeitrag — KI-Tools',
    writeChat2:       'Newsletter-Entwurf',
    travelChat1:      'Japan-Reiseplan',
    codeReviewer:     'Code-Review',
    codeReviewerText: 'Überprüfe den folgenden Code auf Bugs, Sicherheitsprobleme und Best Practices. Schlage konkrete Verbesserungen mit Erklärungen vor.',
    emailPro:         'E-Mail Profi',
    emailProText:     'Verfasse eine professionelle E-Mail für den folgenden Kontext. Sei präzise, klar und höflich im Ton. Beende sie mit meinem Namen.',
    explainSimply:    'Einfach erklären',
    blogOutline:      'Blog-Gliederung',
    debugHelper:      'Debugger',
    debugHelperText:  'Ich habe folgenden Fehler oder unerwartetes Verhalten. Hilf mir, die Grundursache Schritt für Schritt zu diagnostizieren, und schlage dann eine Lösung vor.',
  }),

  es: make({
    title:            'Organiza tus conversaciones de Gemini',
    folderLabel:      '📁 Modo Carpetas',
    promptLabel:      '📝 Modo Prompts',
    folderScreenTitle: 'Ten tus conversaciones siempre ordenadas',
    promptScreenTitle: 'Tus mejores prompts, siempre a mano',
    mobileScreenTitle: 'Accede a tus chats de Gemini desde tu móvil',
    contextMenuScreenTitle: 'Guarda una conversación con un clic derecho',
    ctxMenuSaveLabel: 'Guardar en Carpetas Gemini',
    ctxBack:    'Atrás',
    ctxForward: 'Adelante',
    ctxSavePage: 'Guardar página como…',
    ctxPrint:   'Imprimir…',
    geminiNewChat:           'Chat nuevo',
    geminiMyContent:         'Mi biblioteca',
    geminiDiscussions:       'Conversaciones',
    geminiSettings:          'Configuración y ayuda',
    geminiShowReasoning:     'Mostrar razonamiento',
    geminiInputPlaceholder:  'Escríbele a Gemini',
    geminiTools:             'Herramientas',
    geminiAiReply:           'Aquí tienes una versión refactorizada usando async/await y manejo adecuado de errores…',
    syncFolderName: 'Carpetas Gemini (Sync)',
    research:         'Investigación',
    writing:          'Redacción',
    travel:           'Viajes',
    dev:              'Dev',
    devChat1:         'Refactorizar API Node.js',
    devChat2:         'Depurar hook de React',
    devChat3:         'Escribir pruebas unitarias',
    resChat1:         'Análisis de mercado 2025',
    resChat2:         'Análisis de competidores',
    writeChat1:       'Artículo de blog — IA',
    writeChat2:       'Borrador de newsletter',
    travelChat1:      'Itinerario Japón',
    codeReviewer:     'Revisión de código',
    codeReviewerText: 'Revisa el siguiente código en busca de errores, problemas de seguridad y malas prácticas. Sugiere mejoras concretas con explicaciones.',
    emailPro:         'Email Pro',
    emailProText:     'Redacta un correo electrónico profesional para el siguiente contexto. Sé conciso, claro y usa un tono respetuoso. Firma con mi nombre.',
    explainSimply:    'Explicar fácilmente',
    blogOutline:      'Esquema de blog',
    debugHelper:      'Depurador',
    debugHelperText:  'Tengo el siguiente error o comportamiento inesperado. Ayúdame a diagnosticar la causa raíz paso a paso y luego sugiere una solución.',
  }),

  it: make({
    title:            'Organizza le tue conversazioni Gemini',
    folderLabel:      '📁 Modalità Cartelle',
    promptLabel:      '📝 Modalità Prompt',
    folderScreenTitle: 'Mantieni le tue conversazioni in ordine',
    promptScreenTitle: 'I tuoi prompt migliori, sempre a portata',
    mobileScreenTitle: 'Accedi alle tue chat Gemini dal telefono',
    contextMenuScreenTitle: 'Salva una conversazione con un clic destro',
    ctxMenuSaveLabel: 'Salva in Cartelle Gemini',
    ctxBack:    'Indietro',
    ctxForward: 'Avanti',
    ctxSavePage: 'Salva pagina come…',
    ctxPrint:   'Stampa…',
    geminiNewChat:           'Nuova chat',
    geminiMyContent:         'La mia libreria',
    geminiDiscussions:       'Discussioni',
    geminiSettings:          'Impostazioni e guida',
    geminiShowReasoning:     'Mostra ragionamento',
    geminiInputPlaceholder:  'Chiedi a Gemini',
    geminiTools:             'Strumenti',
    geminiAiReply:           'Ecco una versione refactored pulita con async/await e gestione degli errori…',
    syncFolderName: 'Cartelle Gemini (Sync)',
    research:         'Ricerca',
    writing:          'Scrittura',
    travel:           'Viaggi',
    dev:              'Dev',
    devChat1:         'Refactoring API Node.js',
    devChat2:         'Debug hook React',
    devChat3:         'Scrivere unit test',
    resChat1:         'Analisi di mercato 2025',
    resChat2:         'Panoramica concorrenti',
    writeChat1:       'Articolo blog — AI',
    writeChat2:       'Bozza newsletter',
    travelChat1:      'Itinerario Giappone',
    codeReviewer:     'Code review',
    codeReviewerText: 'Esamina il seguente codice per bug, problemi di sicurezza e best practice. Suggerisci miglioramenti concreti con spiegazioni.',
    emailPro:         'Email Pro',
    emailProText:     'Scrivi un\'email professionale per il seguente contesto. Sii conciso, chiaro e usa un tono educato. Firma con il mio nome.',
    explainSimply:    'Spiega in modo semplice',
    blogOutline:      'Struttura blog',
    debugHelper:      'Debugger',
    debugHelperText:  'Ho il seguente errore o comportamento inaspettato. Aiutami a diagnosticare la causa radice passo dopo passo, poi suggerisci una soluzione.',
  }),

  pt_BR: make({
    title:            'Organize suas conversas do Gemini',
    folderLabel:      '📁 Modo Pastas',
    promptLabel:      '📝 Modo Prompts',
    folderScreenTitle: 'Mantenha suas conversas organizadas',
    promptScreenTitle: 'Seus melhores prompts, sempre à mão',
    mobileScreenTitle: 'Acesse seus chats do Gemini pelo celular',
    contextMenuScreenTitle: 'Salve uma conversa com um clique direito',
    ctxMenuSaveLabel: 'Salvar no Pastas Gemini',
    ctxBack:    'Voltar',
    ctxForward: 'Avançar',
    ctxSavePage: 'Salvar página como…',
    ctxPrint:   'Imprimir…',
    geminiNewChat:           'Novo bate-papo',
    geminiMyContent:         'Minha biblioteca',
    geminiDiscussions:       'Conversas',
    geminiSettings:          'Configurações e ajuda',
    geminiShowReasoning:     'Mostrar raciocínio',
    geminiInputPlaceholder:  'Pergunte ao Gemini',
    geminiTools:             'Ferramentas',
    geminiAiReply:           'Aqui está uma versão refatorada usando async/await e tratamento de erros adequado…',
    syncFolderName: 'Pastas Gemini (Sync)',
    research:         'Pesquisa',
    writing:          'Redação',
    travel:           'Viagens',
    dev:              'Dev',
    devChat1:         'Refatorar API Node.js',
    devChat2:         'Depurar hook React',
    devChat3:         'Escrever testes unitários',
    resChat1:         'Análise de mercado 2025',
    resChat2:         'Visão geral dos concorrentes',
    writeChat1:       'Post de blog — IA',
    writeChat2:       'Rascunho de newsletter',
    travelChat1:      'Roteiro pelo Japão',
    codeReviewer:     'Revisão de código',
    codeReviewerText: 'Revise o código a seguir em busca de bugs, problemas de segurança e boas práticas. Sugira melhorias concretas com explicações.',
    emailPro:         'Email Pro',
    emailProText:     'Escreva um e-mail profissional para o seguinte contexto. Seja conciso, claro e use um tom educado. Assine com meu nome.',
    explainSimply:    'Explique de forma simples',
    blogOutline:      'Esboço de blog',
    debugHelper:      'Depurador',
    debugHelperText:  'Tenho o seguinte erro ou comportamento inesperado. Me ajude a diagnosticar a causa raiz passo a passo e depois sugira uma correção.',
  }),

  pt_PT: make({
    title:            'Organize as suas conversas do Gemini',
    folderLabel:      '📁 Modo Pastas',
    promptLabel:      '📝 Modo Prompts',
    folderScreenTitle: 'Mantenha as suas conversas organizadas',
    promptScreenTitle: 'Os seus melhores prompts, sempre à mão',
    mobileScreenTitle: 'Aceda às suas conversas do Gemini no telemóvel',
    contextMenuScreenTitle: 'Guarde uma conversa com um clique direito',
    ctxMenuSaveLabel: 'Guardar nas Pastas Gemini',
    ctxBack:    'Recuar',
    ctxForward: 'Avançar',
    ctxSavePage: 'Guardar página como…',
    ctxPrint:   'Imprimir…',
    geminiNewChat:           'Nova conversa',
    geminiMyContent:         'A minha biblioteca',
    geminiDiscussions:       'Conversas',
    geminiSettings:          'Definições e ajuda',
    geminiShowReasoning:     'Mostrar raciocínio',
    geminiInputPlaceholder:  'Pergunte ao Gemini',
    geminiTools:             'Ferramentas',
    geminiAiReply:           'Aqui está uma versão refatorada limpa com async/await e tratamento de erros…',
    syncFolderName: 'Pastas Gemini (Sync)',
    research:         'Pesquisa',
    writing:          'Redação',
    travel:           'Viagens',
    dev:              'Dev',
    devChat1:         'Refatorar API Node.js',
    devChat2:         'Depurar hook React',
    devChat3:         'Escrever testes unitários',
    resChat1:         'Análise de mercado 2025',
    resChat2:         'Visão geral dos concorrentes',
    writeChat1:       'Artigo de blog — IA',
    writeChat2:       'Rascunho de newsletter',
    travelChat1:      'Itinerário pelo Japão',
    codeReviewer:     'Revisão de código',
    codeReviewerText: 'Reveja o seguinte código em busca de bugs, problemas de segurança e boas práticas. Sugira melhorias concretas com explicações.',
    emailPro:         'Email Pro',
    emailProText:     'Escreva um e-mail profissional para o seguinte contexto. Seja conciso, claro e use um tom educado. Assine com o meu nome.',
    explainSimply:    'Explique de forma simples',
    blogOutline:      'Esboço de blog',
    debugHelper:      'Depurador',
    debugHelperText:  'Tenho o seguinte erro ou comportamento inesperado. Ajuda-me a diagnosticar a causa raiz passo a passo e depois sugere uma solução.',
  }),

  ru: make({
    title:            'Организуйте беседы в Gemini',
    folderLabel:      '📁 Режим папок',
    promptLabel:      '📝 Режим подсказок',
    folderScreenTitle: 'Держите беседы в порядке',
    promptScreenTitle: 'Лучшие подсказки всегда под рукой',
    mobileScreenTitle: 'Открывайте беседы Gemini с телефона',
    contextMenuScreenTitle: 'Сохраните беседу одним правым кликом',
    ctxMenuSaveLabel: 'Сохранить в Папки Gemini',
    ctxBack:    'Назад',
    ctxForward: 'Вперёд',
    ctxSavePage: 'Сохранить страницу как…',
    ctxPrint:   'Печать…',
    geminiNewChat:           'Новый чат',
    geminiMyContent:         'Моя библиотека',
    geminiDiscussions:       'Обсуждения',
    geminiSettings:          'Настройки и справка',
    geminiShowReasoning:     'Показать рассуждение',
    geminiInputPlaceholder:  'Напишите запрос для Gemini',
    geminiTools:             'Инструменты',
    geminiAiReply:           'Вот чистая рефакторинговая версия с async/await и правильной обработкой ошибок…',
    syncFolderName: 'Папки Gemini (Sync)',
    research:         'Исследования',
    writing:          'Тексты',
    travel:           'Путешествия',
    dev:              'Разр.',
    devChat1:         'Рефакторинг Node.js API',
    devChat2:         'Отладка хука React',
    devChat3:         'Написать юнит-тесты',
    resChat1:         'Анализ рынка 2025',
    resChat2:         'Обзор конкурентов',
    writeChat1:       'Статья в блог — ИИ',
    writeChat2:       'Черновик рассылки',
    travelChat1:      'Маршрут по Японии',
    codeReviewer:     'Ревью кода',
    codeReviewerText: 'Проверь следующий код на наличие ошибок, уязвимостей безопасности и соответствие лучшим практикам. Предложи конкретные улучшения с объяснениями.',
    emailPro:         'Email Pro',
    emailProText:     'Напиши профессиональное письмо для следующего контекста. Будь кратким, чётким и вежливым в тоне. Подпиши своим именем.',
    explainSimply:    'Объясни просто',
    blogOutline:      'План блога',
    debugHelper:      'Помощник отладки',
    debugHelperText:  'У меня следующая ошибка или неожиданное поведение. Помоги мне шаг за шагом определить первопричину, а затем предложи решение.',
  }),

  pl: make({
    title:            'Organizuj rozmowy w Gemini',
    folderLabel:      '📁 Tryb folderów',
    promptLabel:      '📝 Tryb podpowiedzi',
    folderScreenTitle: 'Miej swoje rozmowy w porządku',
    promptScreenTitle: 'Twoje najlepsze prompty zawsze pod ręką',
    mobileScreenTitle: 'Przeglądaj rozmowy Gemini z telefonu',
    contextMenuScreenTitle: 'Zapisz rozmowę jednym prawym kliknięciem',
    ctxMenuSaveLabel: 'Zapisz w Folderach Gemini',
    ctxBack:    'Wstecz',
    ctxForward: 'Dalej',
    ctxSavePage: 'Zapisz stronę jako…',
    ctxPrint:   'Drukuj…',
    geminiNewChat:           'Nowy czat',
    geminiMyContent:         'Moja biblioteka',
    geminiDiscussions:       'Rozmowy',
    geminiSettings:          'Ustawienia i pomoc',
    geminiShowReasoning:     'Pokaż rozumowanie',
    geminiInputPlaceholder:  'Zapytaj Gemini',
    geminiTools:             'Narzędzia',
    geminiAiReply:           'Oto zrefaktoryzowana wersja z async/await i obsługą błędów…',
    syncFolderName: 'Foldery Gemini (Sync)',
    research:         'Badania',
    writing:          'Pisanie',
    travel:           'Podróże',
    dev:              'Dev',
    devChat1:         'Refaktoryzacja API Node.js',
    devChat2:         'Debugowanie hooka React',
    devChat3:         'Pisanie testów jednostkowych',
    resChat1:         'Analiza rynku 2025',
    resChat2:         'Przegląd konkurencji',
    writeChat1:       'Post na blogu — AI',
    writeChat2:       'Szkic newslettera',
    travelChat1:      'Plan podróży do Japonii',
    codeReviewer:     'Przegląd kodu',
    codeReviewerText: 'Sprawdź poniższy kod pod kątem błędów, problemów z bezpieczeństwem i dobrych praktyk. Zaproponuj konkretne ulepszenia z wyjaśnieniami.',
    emailPro:         'Email Pro',
    emailProText:     'Napisz profesjonalny e-mail dla następującego kontekstu. Bądź zwięzły, jasny i używaj uprzejmego tonu. Podpisz swoim imieniem.',
    explainSimply:    'Wyjaśnij prosto',
    blogOutline:      'Konspekt bloga',
    debugHelper:      'Debugger',
    debugHelperText:  'Mam następujący błąd lub nieoczekiwane zachowanie. Pomóż mi zdiagnozować przyczynę krok po kroku, a następnie zaproponuj rozwiązanie.',
  }),

  zh_CN: make({
    title:            '整理您的 Gemini 对话',
    folderLabel:      '📁 文件夹模式',
    promptLabel:      '📝 提示词模式',
    folderScreenTitle: '让对话井然有序',
    promptScreenTitle: '精选提示词，随手可用',
    mobileScreenTitle: '随时从手机访问 Gemini 对话',
    contextMenuScreenTitle: '右键一键保存对话',
    ctxMenuSaveLabel: '保存到 Gemini 文件夹',
    ctxBack:    '返回',
    ctxForward: '前进',
    ctxSavePage: '将网页另存为…',
    ctxPrint:   '打印…',
    geminiNewChat:           '新对话',
    geminiMyContent:         '我的内容',
    geminiDiscussions:       '讨论',
    geminiSettings:          '设置与帮助',
    geminiShowReasoning:     '查看思考过程',
    geminiInputPlaceholder:  '向 Gemini 提问',
    geminiTools:             '工具',
    geminiAiReply:           '这是使用 async/await 的重构版本，包含完善的错误处理…',
    syncFolderName: 'Gemini 文件夹 (同步)',
    research:         '研究',
    writing:          '写作',
    travel:           '旅行',
    dev:              '开发',
    devChat1:         '重构 Node.js API',
    devChat2:         '调试 React Hook',
    devChat3:         '编写单元测试',
    resChat1:         '2025 市场分析',
    resChat2:         '竞争对手概览',
    writeChat1:       '博客文章 — AI 工具',
    writeChat2:       '新闻通讯草稿',
    travelChat1:      '日本行程计划',
    codeReviewer:     '代码审查',
    codeReviewerText: '审查以下代码的错误、安全问题和最佳实践。请提出具体的改进建议并附上说明。',
    emailPro:         '邮件助手',
    emailProText:     '请为以下情境撰写一封专业邮件。要简洁、清晰、语气礼貌，并以我的姓名署名。',
    explainSimply:    '简单解释',
    blogOutline:      '博客提纲',
    debugHelper:      '调试助手',
    debugHelperText:  '我遇到了以下错误或异常行为，请逐步帮我找出根本原因，然后提出修复方案。',
  }),

  ja: make({
    title:            'Gemini の会話を整理しよう',
    folderLabel:      '📁 フォルダモード',
    promptLabel:      '📝 プロンプトモード',
    folderScreenTitle: '会話をすっきり整理しよう',
    promptScreenTitle: '使えるプロンプトをすぐそこに',
    mobileScreenTitle: 'スマホからも Gemini の会話にアクセス',
    contextMenuScreenTitle: '右クリック一発で会話を保存',
    ctxMenuSaveLabel: 'Gemini フォルダに保存',
    ctxBack:    '戻る',
    ctxForward: '進む',
    ctxSavePage: '名前を付けてページを保存…',
    ctxPrint:   '印刷…',
    geminiNewChat:           '新しいチャット',
    geminiMyContent:         'マイライブラリ',
    geminiDiscussions:       '会話',
    geminiSettings:          '設定とヘルプ',
    geminiShowReasoning:     '思考を表示',
    geminiInputPlaceholder:  'Gemini に聞く',
    geminiTools:             'ツール',
    geminiAiReply:           'async/await を使ったクリーンなリファクタリング例と適切なエラー処理です…',
    syncFolderName: 'Gemini フォルダ (Sync)',
    research:         'リサーチ',
    writing:          '執筆',
    travel:           '旅行',
    dev:              '開発',
    devChat1:         'Node.js API リファクタリング',
    devChat2:         'React Hook デバッグ',
    devChat3:         'ユニットテスト作成',
    resChat1:         '市場分析 2025',
    resChat2:         '競合他社概要',
    writeChat1:       'ブログ記事 — AIツール',
    writeChat2:       'ニュースレター草稿',
    travelChat1:      '日本旅行プラン',
    codeReviewer:     'コードレビュー',
    codeReviewerText: '以下のコードのバグ、セキュリティ問題、ベストプラクティスを確認してください。具体的な改善案を説明付きで提案してください。',
    emailPro:         'メール作成',
    emailProText:     '以下の状況に合わせてプロフェッショナルなメールを書いてください。簡潔で明確に、丁寧な言葉遣いで。最後に私の名前で締めてください。',
    explainSimply:    'わかりやすく説明',
    blogOutline:      'ブログ構成',
    debugHelper:      'デバッグ支援',
    debugHelperText:  '以下のエラーまたは予期しない動作が発生しています。根本原因をステップごとに診断し、修正方法を提案してください。',
  }),

  ko: make({
    title:            'Gemini 대화를 정리하세요',
    folderLabel:      '📁 폴더 모드',
    promptLabel:      '📝 프롬프트 모드',
    folderScreenTitle: '대화를 체계적으로 정리하세요',
    promptScreenTitle: '최고의 프롬프트, 언제나 손 닿는 곳에',
    mobileScreenTitle: '휴대폰에서도 Gemini 대화에 접근하세요',
    contextMenuScreenTitle: '우클릭 한 번으로 대화 저장',
    ctxMenuSaveLabel: 'Gemini 폴더에 저장',
    ctxBack:    '뒤로',
    ctxForward: '앞으로',
    ctxSavePage: '다른 이름으로 저장…',
    ctxPrint:   '인쇄…',
    geminiNewChat:           '새 채팅',
    geminiMyContent:         '내 라이브러리',
    geminiDiscussions:       '대화',
    geminiSettings:          '설정 및 도움말',
    geminiShowReasoning:     '추론 표시',
    geminiInputPlaceholder:  'Gemini에게 물어보기',
    geminiTools:             '도구',
    geminiAiReply:           'async/await를 사용한 리팩터링된 버전과 오류 처리입니다…',
    syncFolderName: 'Gemini 폴더 (동기화)',
    research:         '리서치',
    writing:          '글쓰기',
    travel:           '여행',
    dev:              '개발',
    devChat1:         'Node.js API 리팩터링',
    devChat2:         'React Hook 디버깅',
    devChat3:         '단위 테스트 작성',
    resChat1:         '2025 시장 분석',
    resChat2:         '경쟁사 분석',
    writeChat1:       '블로그 포스트 — AI 도구',
    writeChat2:       '뉴스레터 초안',
    travelChat1:      '일본 여행 일정',
    codeReviewer:     '코드 리뷰',
    codeReviewerText: '다음 코드의 버그, 보안 문제, 모범 사례를 검토하세요. 설명과 함께 구체적인 개선 사항을 제안하세요.',
    emailPro:         '이메일 작성',
    emailProText:     '다음 상황에 맞는 전문적인 이메일을 작성하세요. 간결하고 명확하게, 정중한 어조로 작성하고 내 이름으로 마무리하세요.',
    explainSimply:    '쉽게 설명하기',
    blogOutline:      '블로그 개요',
    debugHelper:      '디버그 도우미',
    debugHelperText:  '다음과 같은 오류 또는 예상치 못한 동작이 있습니다. 근본 원인을 단계별로 진단하고 해결 방법을 제안해 주세요.',
  }),

  hi: make({
    title:            'Gemini वार्तालाप व्यवस्थित करें',
    folderLabel:      '📁 फ़ोल्डर मोड',
    promptLabel:      '📝 प्रॉम्प्ट मोड',
    folderScreenTitle: 'बातचीत को व्यवस्थित रखें',
    promptScreenTitle: 'आपके बेहतरीन प्रॉम्प्ट, हमेशा तैयार',
    mobileScreenTitle: 'अपने फ़ोन से Gemini चैट एक्सेस करें',
    contextMenuScreenTitle: 'एक राइट-क्लिक में बातचीत सेव करें',
    ctxMenuSaveLabel: 'Gemini फ़ोल्डर्स में सहेजें',
    ctxBack:    'वापस जाएं',
    ctxForward: 'आगे जाएं',
    ctxSavePage: 'पेज इस रूप में सेव करें…',
    ctxPrint:   'प्रिंट करें…',
    geminiNewChat:           'नई चैट',
    geminiMyContent:         'मेरी लाइब्रेरी',
    geminiDiscussions:       'चर्चाएं',
    geminiSettings:          'सेटिंग और सहायता',
    geminiShowReasoning:     'सोच प्रक्रिया दिखाएं',
    geminiInputPlaceholder:  'Gemini से पूछें',
    geminiTools:             'टूल',
    geminiAiReply:           'async/await का उपयोग करके रिफैक्टर्ड कोड और एरर हैंडलिंग यहाँ है…',
    syncFolderName: 'Gemini फ़ोल्डर्स (Sync)',
    research:         'शोध',
    writing:          'लेखन',
    travel:           'यात्रा',
    dev:              'कोड',
    devChat1:         'Node.js API रीफैक्टर',
    devChat2:         'React Hook डीबग',
    devChat3:         'यूनिट टेस्ट लिखें',
    resChat1:         'बाज़ार विश्लेषण 2025',
    resChat2:         'प्रतिस्पर्धी समीक्षा',
    writeChat1:       'ब्लॉग पोस्ट — AI टूल्स',
    writeChat2:       'न्यूज़लेटर ड्राफ्ट',
    travelChat1:      'जापान यात्रा कार्यक्रम',
    codeReviewer:     'कोड समीक्षा',
    codeReviewerText: 'निम्नलिखित कोड में बग, सुरक्षा समस्याओं और सर्वोत्तम प्रथाओं की जाँच करें। स्पष्टीकरण के साथ ठोस सुधार सुझाएं।',
    emailPro:         'ईमेल सहायक',
    emailProText:     'निम्नलिखित संदर्भ के लिए एक पेशेवर ईमेल लिखें। संक्षिप्त, स्पष्ट और विनम्र रहें। मेरे नाम से समाप्त करें।',
    explainSimply:    'सरलता से समझाएं',
    blogOutline:      'ब्लॉग रूपरेखा',
    debugHelper:      'डीबग सहायक',
    debugHelperText:  'मुझे निम्नलिखित त्रुटि या अप्रत्याशित व्यवहार आ रहा है। कृपया चरण-दर-चरण मूल कारण का निदान करें, फिर एक समाधान सुझाएं।',
  }),

  ro: make({
    title:            'Organizați conversațiile Gemini',
    folderLabel:      '📁 Mod Foldere',
    promptLabel:      '📝 Mod Prompturi',
    folderScreenTitle: 'Organizați-vă conversațiile ușor',
    promptScreenTitle: 'Cele mai bune prompturi, mereu la îndemână',
    mobileScreenTitle: 'Accesați conversațiile Gemini de pe telefon',
    contextMenuScreenTitle: 'Salvați o conversație cu un clic dreapta',
    ctxMenuSaveLabel: 'Salvează în Foldere Gemini',
    ctxBack:    'Înapoi',
    ctxForward: 'Înainte',
    ctxSavePage: 'Salvați pagina ca…',
    ctxPrint:   'Imprimați…',
    geminiNewChat:           'Chat nou',
    geminiMyContent:         'Biblioteca mea',
    geminiDiscussions:       'Conversații',
    geminiSettings:          'Setări și ajutor',
    geminiShowReasoning:     'Afișare raționament',
    geminiInputPlaceholder:  'Întreabă Gemini',
    geminiTools:             'Instrumente',
    geminiAiReply:           'Iată o versiune refactorizată curată cu async/await și gestionarea erorilor…',
    syncFolderName: 'Foldere Gemini (Sync)',
    research:         'Cercetare',
    writing:          'Scriere',
    travel:           'Călătorii',
    dev:              'Dev',
    devChat1:         'Refactorizare API Node.js',
    devChat2:         'Depanare hook React',
    devChat3:         'Scriere teste unitare',
    resChat1:         'Analiză de piață 2025',
    resChat2:         'Prezentare competitori',
    writeChat1:       'Articol blog — instrumente AI',
    writeChat2:       'Ciornă newsletter',
    travelChat1:      'Itinerar Japonia',
    codeReviewer:     'Revizuire cod',
    codeReviewerText: 'Revizuiește codul următor pentru erori, probleme de securitate și bune practici. Sugerează îmbunătățiri concrete cu explicații.',
    emailPro:         'Email Pro',
    emailProText:     'Scrie un e-mail profesional pentru următorul context. Fii concis, clar și folosește un ton politicos. Semnează cu numele meu.',
    explainSimply:    'Explică simplu',
    blogOutline:      'Structură blog',
    debugHelper:      'Depanator',
    debugHelperText:  'Am următoarea eroare sau comportament neașteptat. Ajută-mă să diagnostichez cauza principală pas cu pas, apoi sugerează o soluție.',
  }),

  sk: make({
    title:            'Organizujte konverzácie v Gemini',
    folderLabel:      '📁 Režim priečinkov',
    promptLabel:      '📝 Režim výziev',
    folderScreenTitle: 'Udržujte konverzácie v poriadku',
    promptScreenTitle: 'Vaše najlepšie výzvy, vždy po ruke',
    mobileScreenTitle: 'Prístup k Gemini chatom z telefónu',
    contextMenuScreenTitle: 'Uložte konverzáciu jedným pravým kliknutím',
    ctxMenuSaveLabel: 'Uložiť do Priečinkov Gemini',
    ctxBack:    'Späť',
    ctxForward: 'Dopredu',
    ctxSavePage: 'Uložiť stránku ako…',
    ctxPrint:   'Tlačiť…',
    geminiNewChat:           'Nový chat',
    geminiMyContent:         'Moja knižnica',
    geminiDiscussions:       'Diskusie',
    geminiSettings:          'Nastavenia a pomoc',
    geminiShowReasoning:     'Zobraziť uvažovanie',
    geminiInputPlaceholder:  'Opýtajte sa Gemini',
    geminiTools:             'Nástroje',
    geminiAiReply:           'Tu je čistá refaktorovaná verzia s async/await a spracovaním chýb…',
    syncFolderName: 'Priečinky Gemini (Sync)',
    research:         'Výskum',
    writing:          'Písanie',
    travel:           'Cestovanie',
    dev:              'Vývoj',
    devChat1:         'Refaktorovanie API Node.js',
    devChat2:         'Debugovanie React hooku',
    devChat3:         'Písanie unit testov',
    resChat1:         'Analýza trhu 2025',
    resChat2:         'Prehľad konkurencie',
    writeChat1:       'Blogový príspevok — AI nástroje',
    writeChat2:       'Návrh newslettera',
    travelChat1:      'Plán cesty do Japonska',
    codeReviewer:     'Kontrola kódu',
    codeReviewerText: 'Skontroluj nasledujúci kód na chyby, bezpečnostné problémy a osvedčené postupy. Navrhni konkrétne vylepšenia s vysvetleniami.',
    emailPro:         'Email Pro',
    emailProText:     'Napíš profesionálny e-mail pre nasledujúci kontext. Buď stručný, jasný a zdvorilý v tóne. Podpíš mojím menom.',
    explainSimply:    'Vysvetli jednoducho',
    blogOutline:      'Osnova blogu',
    debugHelper:      'Debugger',
    debugHelperText:  'Mám nasledujúcu chybu alebo neočakávané správanie. Pomôž mi diagnostikovať hlavnú príčinu krok za krokom a potom navrhni opravu.',
  }),

  cs: make({
    title:            'Organizujte konverzace v Gemini',
    folderLabel:      '📁 Režim složek',
    promptLabel:      '📝 Režim výzev',
    folderScreenTitle: 'Mějte konverzace přehledně seřazeny',
    promptScreenTitle: 'Vaše nejlepší výzvy, vždy po ruce',
    mobileScreenTitle: 'Přístup k Gemini chatům z telefonu',
    contextMenuScreenTitle: 'Uložte konverzaci jedním pravým kliknutím',
    ctxMenuSaveLabel: 'Uložit do Složek Gemini',
    ctxBack:    'Zpět',
    ctxForward: 'Vpřed',
    ctxSavePage: 'Uložit stránku jako…',
    ctxPrint:   'Tisk…',
    geminiNewChat:           'Nový chat',
    geminiMyContent:         'Moje knihovna',
    geminiDiscussions:       'Diskuse',
    geminiSettings:          'Nastavení a nápověda',
    geminiShowReasoning:     'Zobrazit uvažování',
    geminiInputPlaceholder:  'Zeptejte se Gemini',
    geminiTools:             'Nástroje',
    geminiAiReply:           'Zde je čistá refaktorovaná verze s async/await a zpracováním chyb…',
    syncFolderName: 'Složky Gemini (Sync)',
    research:         'Výzkum',
    writing:          'Psaní',
    travel:           'Cestování',
    dev:              'Vývoj',
    devChat1:         'Refaktorizace API Node.js',
    devChat2:         'Ladění hooku React',
    devChat3:         'Psaní unit testů',
    resChat1:         'Analýza trhu 2025',
    resChat2:         'Přehled konkurence',
    writeChat1:       'Blogový příspěvek — AI nástroje',
    writeChat2:       'Návrh newsletteru',
    travelChat1:      'Itinerář do Japonska',
    codeReviewer:     'Kontrola kódu',
    codeReviewerText: 'Zkontroluj následující kód na chyby, bezpečnostní problémy a osvědčené postupy. Navrhni konkrétní vylepšení s vysvětleními.',
    emailPro:         'Email Pro',
    emailProText:     'Napiš profesionální e-mail pro následující kontext. Buď stručný, jasný a zdvořilý v tónu. Podpiš mým jménem.',
    explainSimply:    'Vysvětli jednoduše',
    blogOutline:      'Osnova blogu',
    debugHelper:      'Debugger',
    debugHelperText:  'Mám následující chybu nebo neočekávané chování. Pomoz mi diagnostikovat hlavní příčinu krok za krokem a pak navrhni opravu.',
  }),

  zh_TW: make({
    title:            '整理您的 Gemini 對話',
    folderLabel:      '📁 資料夾模式',
    promptLabel:      '📝 提示詞模式',
    folderScreenTitle: '讓您的對話保持井然有序',
    promptScreenTitle: '最佳提示詞，隨時就緒',
    mobileScreenTitle: '在手機上存取您的 Gemini 對話',
    contextMenuScreenTitle: '一鍵右鍵儲存對話',
    ctxMenuSaveLabel: '儲存到 Gemini 資料夾',
    ctxBack:    '返回',
    ctxForward: '前進',
    ctxSavePage: '另存網頁…',
    ctxPrint:   '列印…',
    geminiNewChat:           '新對話',
    geminiMyContent:         '我的內容',
    geminiDiscussions:       '討論',
    geminiSettings:          '設定與說明',
    geminiShowReasoning:     '顯示思考過程',
    geminiInputPlaceholder:  '詢問 Gemini',
    geminiTools:             '工具',
    geminiAiReply:           '以下是使用 async/await 和適當錯誤處理的整理後版本…',
    syncFolderName: 'Gemini 資料夾 (同步)',
    research:         '研究',
    writing:          '寫作',
    travel:           '旅遊',
    dev:              '開發',
    devChat1:         '重構 Node.js API',
    devChat2:         '除錯 React Hook',
    devChat3:         '撰寫單元測試',
    resChat1:         '2025 市場分析',
    resChat2:         '競爭對手概覽',
    writeChat1:       '部落格文章 — AI 生產力',
    writeChat2:       '電子報草稿',
    travelChat1:      '日本旅行行程',
    codeReviewer:     '程式碼審查',
    codeReviewerText: '審查以下程式碼的錯誤、安全問題和最佳實踐。請提出具體的改進建議並附上說明。',
    emailPro:         '電子郵件專家',
    emailProText:     '為以下情境撰寫一封專業電子郵件。請簡潔、清晰，並使用禮貌的語氣。以我的名字署名。',
    explainSimply:    '簡單解釋',
    blogOutline:      '部落格大綱',
    debugHelper:      '除錯助手',
    debugHelperText:  '我遇到了以下錯誤或意外行為。請逐步協助我診斷根本原因，然後建議修復方法。',
  }),

  id: make({
    title:            'Susun percakapan Gemini Anda',
    folderLabel:      '📁 Mode Folder',
    promptLabel:      '📝 Mode Prompt',
    folderScreenTitle: 'Jaga percakapan Anda tetap teratur',
    promptScreenTitle: 'Prompt terbaik Anda, selalu siap',
    mobileScreenTitle: 'Akses obrolan Gemini dari ponsel Anda',
    contextMenuScreenTitle: 'Simpan percakapan dengan satu klik kanan',
    ctxMenuSaveLabel: 'Simpan ke Folder Gemini',
    ctxBack:    'Kembali',
    ctxForward: 'Maju',
    ctxSavePage: 'Simpan halaman sebagai…',
    ctxPrint:   'Cetak…',
    geminiNewChat:           'Obrolan baru',
    geminiMyContent:         'Konten saya',
    geminiDiscussions:       'Diskusi',
    geminiSettings:          'Setelan & bantuan',
    geminiShowReasoning:     'Tampilkan pemikiran',
    geminiInputPlaceholder:  'Tanya Gemini',
    geminiTools:             'Alat',
    geminiAiReply:           'Berikut versi yang telah direfaktor dengan async/await dan penanganan error yang tepat…',
    syncFolderName: 'Folder Gemini (Sync)',
    research:         'Riset',
    writing:          'Penulisan',
    travel:           'Perjalanan',
    dev:              'Pengembangan',
    devChat1:         'Refaktor API Node.js',
    devChat2:         'Debug React Hook',
    devChat3:         'Tulis Unit Test',
    resChat1:         'Analisis Pasar 2025',
    resChat2:         'Tinjauan Pesaing',
    writeChat1:       'Artikel Blog — Produktivitas AI',
    writeChat2:       'Draf Newsletter',
    travelChat1:      'Rencana Perjalanan Jepang',
    codeReviewer:     'Tinjauan Kode',
    codeReviewerText: 'Tinjau kode berikut untuk bug, masalah keamanan, dan praktik terbaik. Sarankan perbaikan konkret dengan penjelasan.',
    emailPro:         'Email Pro',
    emailProText:     'Tulis email profesional untuk konteks berikut. Jadilah ringkas, jelas, dan gunakan nada sopan. Tandatangani dengan nama saya.',
    explainSimply:    'Jelaskan dengan Sederhana',
    blogOutline:      'Kerangka Blog',
    debugHelper:      'Pembantu Debug',
    debugHelperText:  'Saya memiliki error atau perilaku tak terduga berikut. Bantu saya mendiagnosis akar masalah langkah demi langkah, lalu sarankan perbaikan.',
  }),

  hu: make({
    title:            'Rendszerezze Gemini-beszélgetéseit',
    folderLabel:      '📁 Mappaüzemmód',
    promptLabel:      '📝 Promptüzemmód',
    folderScreenTitle: 'Tartsa rendben a beszélgetéseit',
    promptScreenTitle: 'Legjobb promptjai, mindig kéznél',
    mobileScreenTitle: 'Érje el Gemini-csevegéseit telefonján',
    contextMenuScreenTitle: 'Mentse el a beszélgetést egy jobb kattintással',
    ctxMenuSaveLabel: 'Mentés a Gemini Mappákba',
    ctxBack:    'Vissza',
    ctxForward: 'Előre',
    ctxSavePage: 'Oldal mentése másként…',
    ctxPrint:   'Nyomtatás…',
    geminiNewChat:           'Új csevegés',
    geminiMyContent:         'Saját tartalom',
    geminiDiscussions:       'Beszélgetések',
    geminiSettings:          'Beállítások és súgó',
    geminiShowReasoning:     'Gondolkodás megjelenítése',
    geminiInputPlaceholder:  'Kérdezzen a Geminitől',
    geminiTools:             'Eszközök',
    geminiAiReply:           'Íme az async/await és megfelelő hibakezeléssel refaktorált verzió…',
    syncFolderName: 'Gemini Mappák (Sync)',
    research:         'Kutatás',
    writing:          'Írás',
    travel:           'Utazás',
    dev:              'Fejlesztés',
    devChat1:         'Node.js API refaktorálása',
    devChat2:         'React Hook hibakeresése',
    devChat3:         'Egységtesztek írása',
    resChat1:         'Piacelemzés 2025',
    resChat2:         'Versenytárs-áttekintés',
    writeChat1:       'Blogbejegyzés — AI-termelékenység',
    writeChat2:       'Hírlevél-tervezet',
    travelChat1:      'Japán utazási terv',
    codeReviewer:     'Kódátvizsgáló',
    codeReviewerText: 'Vizsgálja át az alábbi kódot hibák, biztonsági problémák és bevált módszerek szempontjából. Javasoljon konkrét fejlesztéseket magyarázatokkal.',
    emailPro:         'E-mail-szakértő',
    emailProText:     'Írjon professzionális e-mailt az alábbi kontextushoz. Legyen tömör, világos, és használjon udvarias hangnemet. Írja alá a nevemmel.',
    explainSimply:    'Egyszerű magyarázat',
    blogOutline:      'Blogvázlat',
    debugHelper:      'Hibakereső segítő',
    debugHelperText:  'Az alábbi hiba vagy váratlan viselkedés tapasztalható. Segítsen lépésről lépésre diagnosztizálni az okát, majd javasoljon megoldást.',
  }),

  th: make({
    title:            'จัดระเบียบการสนทนา Gemini ของคุณ',
    folderLabel:      '📁 โหมดโฟลเดอร์',
    promptLabel:      '📝 โหมดพรอมต์',
    folderScreenTitle: 'เก็บการสนทนาของคุณให้เป็นระเบียบ',
    promptScreenTitle: 'พรอมต์ที่ดีที่สุดของคุณ พร้อมเสมอ',
    mobileScreenTitle: 'เข้าถึงแชท Gemini จากโทรศัพท์ของคุณ',
    contextMenuScreenTitle: 'บันทึกการสนทนาด้วยการคลิกขวาครั้งเดียว',
    ctxMenuSaveLabel: 'บันทึกไปยังโฟลเดอร์ Gemini',
    ctxBack:    'ย้อนกลับ',
    ctxForward: 'ไปข้างหน้า',
    ctxSavePage: 'บันทึกหน้าเว็บเป็น…',
    ctxPrint:   'พิมพ์…',
    geminiNewChat:           'แชทใหม่',
    geminiMyContent:         'เนื้อหาของฉัน',
    geminiDiscussions:       'การสนทนา',
    geminiSettings:          'การตั้งค่าและความช่วยเหลือ',
    geminiShowReasoning:     'แสดงการคิด',
    geminiInputPlaceholder:  'ถาม Gemini',
    geminiTools:             'เครื่องมือ',
    geminiAiReply:           'นี่คือเวอร์ชันที่ปรับปรุงใหม่โดยใช้ async/await และการจัดการข้อผิดพลาดที่เหมาะสม…',
    syncFolderName: 'โฟลเดอร์ Gemini (Sync)',
    research:         'การวิจัย',
    writing:          'การเขียน',
    travel:           'การท่องเที่ยว',
    dev:              'การพัฒนา',
    devChat1:         'รีแฟกเตอร์ API Node.js',
    devChat2:         'ดีบัก React Hook',
    devChat3:         'เขียน Unit Test',
    resChat1:         'วิเคราะห์ตลาด 2025',
    resChat2:         'ภาพรวมคู่แข่ง',
    writeChat1:       'บล็อกโพสต์ — AI Productivity',
    writeChat2:       'ร่างจดหมายข่าว',
    travelChat1:      'แผนการเดินทางญี่ปุ่น',
    codeReviewer:     'ตรวจสอบโค้ด',
    codeReviewerText: 'ตรวจสอบโค้ดต่อไปนี้สำหรับบัก ปัญหาด้านความปลอดภัย และแนวทางปฏิบัติที่ดีที่สุด แนะนำการปรับปรุงที่เป็นรูปธรรมพร้อมคำอธิบาย',
    emailPro:         'ผู้เชี่ยวชาญอีเมล',
    emailProText:     'เขียนอีเมลระดับมืออาชีพสำหรับบริบทต่อไปนี้ ให้กระชับ ชัดเจน และใช้น้ำเสียงที่สุภาพ ลงชื่อด้วยชื่อของฉัน',
    explainSimply:    'อธิบายให้เข้าใจง่าย',
    blogOutline:      'โครงร่างบล็อก',
    debugHelper:      'ผู้ช่วยดีบัก',
    debugHelperText:  'ฉันมีข้อผิดพลาดหรือพฤติกรรมที่ไม่คาดคิดต่อไปนี้ ช่วยฉันวินิจฉัยสาเหตุหลักทีละขั้นตอน แล้วแนะนำวิธีแก้ไข',
  }),

  tl: make({
    title:            'Ayusin ang iyong mga pag-uusap sa Gemini',
    folderLabel:      '📁 Folder Mode',
    promptLabel:      '📝 Prompt Mode',
    folderScreenTitle: 'Panatilihing maayos ang iyong mga pag-uusap',
    promptScreenTitle: 'Ang iyong mga pinakamahusay na prompt, laging handa',
    mobileScreenTitle: 'I-access ang mga Gemini chat sa iyong telepono',
    contextMenuScreenTitle: 'I-save ang pag-uusap sa isang right-click',
    ctxMenuSaveLabel: 'I-save sa Mga Folder ng Gemini',
    ctxBack:    'Bumalik',
    ctxForward: 'Sulong',
    ctxSavePage: 'I-save ang pahina bilang…',
    ctxPrint:   'I-print…',
    geminiNewChat:           'Bagong chat',
    geminiMyContent:         'Ang aking nilalaman',
    geminiDiscussions:       'Mga talakayan',
    geminiSettings:          'Mga setting at tulong',
    geminiShowReasoning:     'Ipakita ang pag-iisip',
    geminiInputPlaceholder:  'Tanungin ang Gemini',
    geminiTools:             'Mga tool',
    geminiAiReply:           'Narito ang refactored na bersyon na may async/await at wastong error handling…',
    syncFolderName: 'Mga Folder ng Gemini (Sync)',
    research:         'Pananaliksik',
    writing:          'Pagsusulat',
    travel:           'Paglalakbay',
    dev:              'Pagbuo',
    devChat1:         'Refactor ng Node.js API',
    devChat2:         'Debug ng React Hook',
    devChat3:         'Pagsulat ng Unit Tests',
    resChat1:         'Pagsusuri ng Merkado 2025',
    resChat2:         'Pangkalahatang-ideya ng Kakumpitensya',
    writeChat1:       'Blog Post — AI Productivity',
    writeChat2:       'Draft ng Newsletter',
    travelChat1:      'Itinerary sa Japan',
    codeReviewer:     'Code Reviewer',
    codeReviewerText: 'Suriin ang sumusunod na code para sa mga bug, isyu sa seguridad, at pinakamahusay na gawi. Magmungkahi ng mga konkretong pagpapabuti na may mga paliwanag.',
    emailPro:         'Email Pro',
    emailProText:     'Sumulat ng propesyonal na email para sa sumusunod na konteksto. Maging maigsi, malinaw, at gumamit ng magalang na tono. Lagdaan ng aking pangalan.',
    explainSimply:    'Ipaliwanag nang Simple',
    blogOutline:      'Blog Outline',
    debugHelper:      'Debug Helper',
    debugHelperText:  'Mayroon akong sumusunod na error o hindi inaasahang gawi. Tulungan mo akong i-diagnose ang ugat na sanhi nang hakbang-hakbang, pagkatapos ay magmungkahi ng solusyon.',
  }),

  sw: make({
    title:            'Panga mazungumzo yako ya Gemini',
    folderLabel:      '📁 Hali ya Folda',
    promptLabel:      '📝 Hali ya Kidokezo',
    folderScreenTitle: 'Weka mazungumzo yako yaliyopangwa',
    promptScreenTitle: 'Vidokezo vyako bora, tayari daima',
    mobileScreenTitle: 'Fikia mazungumzo ya Gemini kwenye simu yako',
    contextMenuScreenTitle: 'Hifadhi mazungumzo kwa kubofya kulia mara moja',
    ctxMenuSaveLabel: 'Hifadhi kwenye Folda za Gemini',
    ctxBack:    'Rudi',
    ctxForward: 'Endelea',
    ctxSavePage: 'Hifadhi ukurasa kama…',
    ctxPrint:   'Chapisha…',
    geminiNewChat:           'Mazungumzo mapya',
    geminiMyContent:         'Maudhui yangu',
    geminiDiscussions:       'Majadiliano',
    geminiSettings:          'Mipangilio na msaada',
    geminiShowReasoning:     'Onyesha hoja',
    geminiInputPlaceholder:  'Uliza Gemini',
    geminiTools:             'Zana',
    geminiAiReply:           'Hapa kuna toleo lililoimarishwa na async/await na kushughulikia makosa ipasavyo…',
    syncFolderName: 'Folda za Gemini (Sync)',
    research:         'Utafiti',
    writing:          'Uandishi',
    travel:           'Usafiri',
    dev:              'Maendeleo',
    devChat1:         'Rejesha API ya Node.js',
    devChat2:         'Debug React Hook',
    devChat3:         'Andika Majaribio ya Unit',
    resChat1:         'Uchambuzi wa Soko 2025',
    resChat2:         'Mapitio ya Washindani',
    writeChat1:       'Makala ya Blogu — Tija ya AI',
    writeChat2:       'Rasimu ya Jarida',
    travelChat1:      'Ratiba ya Safari ya Japan',
    codeReviewer:     'Mkaguzi wa Msimbo',
    codeReviewerText: 'Kagua msimbo ufuatao kwa hitilafu, matatizo ya usalama na mbinu bora. Pendekeza maboresho maalum na maelezo.',
    emailPro:         'Mtaalamu wa Barua Pepe',
    emailProText:     'Andika barua pepe ya kitaalamu kwa muktadha ufuatao. Kuwa mfupi, wazi na utumie sauti ya heshima. Saini kwa jina langu.',
    explainSimply:    'Eleza kwa Urahisi',
    blogOutline:      'Muhtasari wa Blogu',
    debugHelper:      'Msaidizi wa Debug',
    debugHelperText:  'Nina hitilafu au tabia isiyotarajiwa ifuatayo. Nisaidie kuchunguza sababu kuu hatua kwa hatua, kisha pendekeza suluhisho.',
  }),

  nl: make({
    title:            'Organiseer uw Gemini-gesprekken',
    folderLabel:      '📁 Mappenmodus',
    promptLabel:      '📝 Promptmodus',
    folderScreenTitle: 'Houd uw gesprekken altijd geordend',
    promptScreenTitle: 'Uw beste prompts, altijd klaar',
    mobileScreenTitle: 'Toegang tot Gemini-chats op uw telefoon',
    contextMenuScreenTitle: 'Sla een gesprek op met één rechtsklik',
    ctxMenuSaveLabel: 'Opslaan in Gemini Mappen',
    ctxBack:    'Terug',
    ctxForward: 'Vooruit',
    ctxSavePage: 'Pagina opslaan als…',
    ctxPrint:   'Afdrukken…',
    geminiNewChat:           'Nieuw gesprek',
    geminiMyContent:         'Mijn inhoud',
    geminiDiscussions:       'Discussies',
    geminiSettings:          'Instellingen & help',
    geminiShowReasoning:     'Redenering tonen',
    geminiInputPlaceholder:  'Vraag Gemini',
    geminiTools:             'Tools',
    geminiAiReply:           'Hier is de gerefactorde versie met async/await en correcte foutafhandeling…',
    syncFolderName: 'Gemini Mappen (Sync)',
    research:         'Onderzoek',
    writing:          'Schrijven',
    travel:           'Reizen',
    dev:              'Ontwikkeling',
    devChat1:         'Node.js API refactoren',
    devChat2:         'React Hook debuggen',
    devChat3:         'Unit tests schrijven',
    resChat1:         'Marktanalyse 2025',
    resChat2:         'Concurrentieoverzicht',
    writeChat1:       'Blogbericht — AI-productiviteit',
    writeChat2:       'Nieuwsbrief concept',
    travelChat1:      'Japan reisroute',
    codeReviewer:     'Codereviewer',
    codeReviewerText: 'Bekijk de volgende code op bugs, beveiligingsproblemen en best practices. Stel concrete verbeteringen voor met uitleg.',
    emailPro:         'E-mailprofessional',
    emailProText:     'Schrijf een professionele e-mail voor de volgende context. Wees beknopt, duidelijk en gebruik een beleefde toon. Onderteken met mijn naam.',
    explainSimply:    'Eenvoudig uitleggen',
    blogOutline:      'Blogopzet',
    debugHelper:      'Debug-assistent',
    debugHelperText:  'Ik heb de volgende fout of onverwacht gedrag. Help me de hoofdoorzaak stap voor stap te diagnosticeren en stel dan een oplossing voor.',
  }),

  bn: make({
    title:            'আপনার Gemini কথোপকথন সংগঠিত করুন',
    folderLabel:      '📁 ফোল্ডার মোড',
    promptLabel:      '📝 প্রম্পট মোড',
    folderScreenTitle: 'কথোপকথন সবসময় গুছানো রাখুন',
    promptScreenTitle: 'আপনার সেরা প্রম্পট, সবসময় প্রস্তুত',
    mobileScreenTitle: 'ফোনে Gemini চ্যাট অ্যাক্সেস করুন',
    contextMenuScreenTitle: 'এক রাইট-ক্লিকে কথোপকথন সংরক্ষণ',
    ctxMenuSaveLabel: 'Gemini ফোল্ডার-এ সংরক্ষণ করুন',
    ctxBack:    'পিছনে',
    ctxForward: 'সামনে',
    ctxSavePage: 'পৃষ্ঠাটি সংরক্ষণ করুন…',
    ctxPrint:   'প্রিন্ট করুন…',
    geminiNewChat:           'নতুন চ্যাট',
    geminiMyContent:         'আমার কন্টেন্ট',
    geminiDiscussions:       'আলোচনা',
    geminiSettings:          'সেটিংস ও সাহায্য',
    geminiShowReasoning:     'যুক্তি দেখান',
    geminiInputPlaceholder:  'Gemini-কে জিজ্ঞাসা করুন',
    geminiTools:             'টুলস',
    geminiAiReply:           'এখানে async/await এবং সঠিক এরর হ্যান্ডলিং সহ রিফ্যাক্টর করা সংস্করণ রয়েছে…',
    syncFolderName: 'Gemini ফোল্ডার (Sync)',
    research:         'গবেষণা',
    writing:          'লেখালেখি',
    travel:           'ভ্রমণ',
    dev:              'ডেভেলপমেন্ট',
    devChat1:         'Node.js API রিফ্যাক্টর',
    devChat2:         'React Hook ডিবাগ',
    devChat3:         'Unit Test লেখা',
    resChat1:         '২০২৫ বাজার বিশ্লেষণ',
    resChat2:         'প্রতিযোগী পর্যালোচনা',
    writeChat1:       'ব্লগ পোস্ট — AI উৎপাদনশীলতা',
    writeChat2:       'নিউজলেটার খসড়া',
    travelChat1:      'জাপান ভ্রমণ পরিকল্পনা',
    codeReviewer:     'কোড রিভিউ',
    codeReviewerText: 'নিম্নলিখিত কোডটি বাগ, নিরাপত্তা সমস্যা এবং সেরা পদ্ধতির জন্য পর্যালোচনা করুন। ব্যাখ্যাসহ নির্দিষ্ট উন্নতির পরামর্শ দিন।',
    emailPro:         'ইমেইল বিশেষজ্ঞ',
    emailProText:     'নিম্নলিখিত প্রসঙ্গের জন্য একটি পেশাদার ইমেইল লিখুন। সংক্ষিপ্ত, স্পষ্ট এবং বিনম্র স্বরে লিখুন। আমার নামে স্বাক্ষর করুন।',
    explainSimply:    'সহজভাবে ব্যাখ্যা করুন',
    blogOutline:      'ব্লগ রূপরেখা',
    debugHelper:      'ডিবাগ সহায়তা',
    debugHelperText:  'আমার নিম্নলিখিত ত্রুটি বা অপ্রত্যাশিত আচরণ রয়েছে। ধাপে ধাপে মূল কারণ নির্ণয় করতে সাহায্য করুন, তারপর একটি সমাধান পরামর্শ দিন।',
  }),

  vi: make({
    title:            'Sắp xếp các cuộc trò chuyện Gemini của bạn',
    folderLabel:      '📁 Chế độ thư mục',
    promptLabel:      '📝 Chế độ prompt',
    folderScreenTitle: 'Giữ các cuộc trò chuyện luôn ngăn nắp',
    promptScreenTitle: 'Prompt tốt nhất của bạn, luôn sẵn sàng',
    mobileScreenTitle: 'Truy cập chat Gemini từ điện thoại',
    contextMenuScreenTitle: 'Lưu cuộc trò chuyện bằng một cú nhấp chuột phải',
    ctxMenuSaveLabel: 'Lưu vào Thư mục Gemini',
    ctxBack:    'Quay lại',
    ctxForward: 'Tiến',
    ctxSavePage: 'Lưu trang dưới dạng…',
    ctxPrint:   'In…',
    geminiNewChat:           'Chat mới',
    geminiMyContent:         'Nội dung của tôi',
    geminiDiscussions:       'Thảo luận',
    geminiSettings:          'Cài đặt & trợ giúp',
    geminiShowReasoning:     'Hiển thị lý luận',
    geminiInputPlaceholder:  'Hỏi Gemini',
    geminiTools:             'Công cụ',
    geminiAiReply:           'Đây là phiên bản đã được tái cấu trúc với async/await và xử lý lỗi phù hợp…',
    syncFolderName: 'Thư mục Gemini (Sync)',
    research:         'Nghiên cứu',
    writing:          'Viết lách',
    travel:           'Du lịch',
    dev:              'Lập trình',
    devChat1:         'Tái cấu trúc API Node.js',
    devChat2:         'Debug React Hook',
    devChat3:         'Viết Unit Test',
    resChat1:         'Phân tích thị trường 2025',
    resChat2:         'Tổng quan đối thủ cạnh tranh',
    writeChat1:       'Bài viết blog — Năng suất AI',
    writeChat2:       'Bản nháp bản tin',
    travelChat1:      'Lịch trình Nhật Bản',
    codeReviewer:     'Xem xét code',
    codeReviewerText: 'Xem xét đoạn code sau để tìm lỗi, vấn đề bảo mật và các phương pháp tốt nhất. Đề xuất các cải tiến cụ thể kèm giải thích.',
    emailPro:         'Chuyên gia Email',
    emailProText:     'Viết một email chuyên nghiệp cho ngữ cảnh sau. Hãy ngắn gọn, rõ ràng và lịch sự. Ký tên tôi.',
    explainSimply:    'Giải thích đơn giản',
    blogOutline:      'Dàn ý blog',
    debugHelper:      'Trợ lý gỡ lỗi',
    debugHelperText:  'Tôi gặp lỗi hoặc hành vi không mong đợi sau đây. Hãy giúp tôi chẩn đoán nguyên nhân gốc rễ từng bước, sau đó đề xuất cách khắc phục.',
  }),

  tr: make({
    title:            'Gemini konuşmalarınızı düzenleyin',
    folderLabel:      '📁 Klasör Modu',
    promptLabel:      '📝 İstem Modu',
    folderScreenTitle: 'Konuşmalarınızı düzenli tutun',
    promptScreenTitle: 'En iyi istemleriniz, her zaman hazır',
    mobileScreenTitle: 'Gemini sohbetlerinize telefonunuzdan erişin',
    contextMenuScreenTitle: 'Bir konuşmayı tek sağ tıkla kaydedin',
    ctxMenuSaveLabel: "Gemini Klasörler'e Kaydet",
    ctxBack:    'Geri',
    ctxForward: 'İleri',
    ctxSavePage: 'Sayfayı farklı kaydet…',
    ctxPrint:   'Yazdır…',
    geminiNewChat:           'Yeni sohbet',
    geminiMyContent:         'İçeriklerim',
    geminiDiscussions:       'Sohbetler',
    geminiSettings:          'Ayarlar ve yardım',
    geminiShowReasoning:     'Düşünceyi göster',
    geminiInputPlaceholder:  "Gemini'ye sor",
    geminiTools:             'Araçlar',
    geminiAiReply:           'async/await ve uygun hata yönetimi kullanılarak yazılmış temiz bir yeniden düzenlenmiş sürüm…',
    syncFolderName: 'Gemini Klasörler (Sync)',
    research:         'Araştırma',
    writing:          'Yazım',
    travel:           'Seyahat',
    dev:              'Geliştirme',
    devChat1:         'Node.js API Refaktöre Et',
    devChat2:         'React Hook Hata Ayıkla',
    devChat3:         'Birim Testleri Yaz',
    resChat1:         'Pazar Analizi 2025',
    resChat2:         'Rekabetçi Genel Bakış',
    writeChat1:       'Blog Yazısı — Yapay Zeka Verimliliği',
    writeChat2:       'Bülten Taslağı',
    travelChat1:      'Japonya Gezi Planı',
    codeReviewer:     'Kod İnceleme',
    codeReviewerText: 'Aşağıdaki kodu hatalar, güvenlik sorunları ve en iyi uygulamalar açısından inceleyin. Açıklamalarla birlikte somut iyileştirmeler önerin.',
    emailPro:         'E-posta Uzmanı',
    emailProText:     'Aşağıdaki bağlam için profesyonel bir e-posta yazın. Kısa, net ve kibarca bir tonla yazın. Adımla imzalayın.',
    explainSimply:    'Basitçe Açıkla',
    blogOutline:      'Blog Taslağı',
    debugHelper:      'Hata Ayıklama Yardımcısı',
    debugHelperText:  'Aşağıdaki hata veya beklenmedik davranışa sahibim. Kök nedeni adım adım teşhis etmeme yardımcı olun, ardından bir düzeltme önerin.',
  }),

};
