/**
 * Localized sample data for all 16 supported locales.
 * Folder names, prompt titles/texts, conversation titles, and UI labels
 * are all translated. Defaults fall back to English where omitted.
 */

const NOW = Date.now();
const DAY = 86400000;

function make(locale) {
  const {
    title, folderLabel, promptLabel,
    research, writing, travel,
    dev          = 'Dev',
    // Conversation titles (English defaults)
    devChat1     = 'Refactor Node.js API',
    devChat2     = 'Debug React hook',
    devChat3     = 'Write unit tests',
    resChat1     = 'Market analysis 2025',
    resChat2     = 'Competitor overview',
    writeChat1   = 'Blog post — AI productivity',
    writeChat2   = 'Newsletter draft',
    travelChat1  = 'Japan trip itinerary',
    // Prompt titles/texts
    codeReviewer, codeReviewerText,
    emailPro,     emailProText,
    explainSimply, blogOutline,
    debugHelper     = 'Debug Helper',
    debugHelperText = 'I have the following error or unexpected behavior. Help me diagnose the root cause step by step, then suggest a fix.',
  } = locale;

  return {
    title,
    folderLabel,
    promptLabel,
    pinnedFolders: [`💻 ${dev}`],
    folders: {
      [`💻 ${dev}`]: [
        { url: 'https://gemini.google.com/app/aaa1', title: devChat1,    timestamp: NOW - 1 * DAY },
        { url: 'https://gemini.google.com/app/aaa2', title: devChat2,    timestamp: NOW - 2 * DAY },
        { url: 'https://gemini.google.com/app/aaa3', title: devChat3,    timestamp: NOW - 3 * DAY },
      ],
      [`📊 ${research}`]: [
        { url: 'https://gemini.google.com/app/bbb1', title: resChat1,    timestamp: NOW - 4 * DAY },
        { url: 'https://gemini.google.com/app/bbb2', title: resChat2,    timestamp: NOW - 5 * DAY },
      ],
      [`✍️ ${writing}`]: [
        { url: 'https://gemini.google.com/app/ccc1', title: writeChat1,  timestamp: NOW - 6 * DAY },
        { url: 'https://gemini.google.com/app/ccc2', title: writeChat2,  timestamp: NOW - 7 * DAY },
      ],
      [`🌍 ${travel}`]: [
        { url: 'https://gemini.google.com/app/ddd1', title: travelChat1, timestamp: NOW - 8 * DAY },
      ],
    },
    prompts: {
      [codeReviewer]: {
        text: codeReviewerText,
        timestamp: NOW - 1 * DAY,
        pinned: true,
      },
      [emailPro]: {
        text: emailProText,
        timestamp: NOW - 2 * DAY,
        pinned: true,
      },
      [explainSimply]: {
        text: 'Explain the following concept as if I were 12 years old, using simple words and a concrete real-world analogy.',
        timestamp: NOW - 3 * DAY,
      },
      [blogOutline]: {
        text: 'Create a structured outline for a blog post about the following topic: introduction, 5 main sections with key points, and a conclusion.',
        timestamp: NOW - 4 * DAY,
      },
      [debugHelper]: {
        text: debugHelperText,
        timestamp: NOW - 5 * DAY,
      },
    },
  };
}

// ─── Locale definitions ───────────────────────────────────────────────────────

module.exports = {

  en: make({
    title:            'Organize your Gemini conversations',
    folderLabel:      '📁 Folder Mode',
    promptLabel:      '📝 Prompt Mode',
    research:         'Research',
    writing:          'Writing',
    travel:           'Travel',
    codeReviewer:     'Code Reviewer',
    codeReviewerText: 'Review the following code for bugs, security issues, and best practices. Suggest concrete improvements with explanations.',
    emailPro:         'Email Pro',
    emailProText:     'Write a professional email for the following context. Be concise, clear, and use a polite tone. Sign off with my name.',
    explainSimply:    'Explain Simply',
    blogOutline:      'Blog Outline',
  }),

  fr: make({
    title:            'Organisez vos conversations Gemini',
    folderLabel:      '📁 Mode Dossiers',
    promptLabel:      '📝 Mode Prompts',
    research:         'Recherche',
    writing:          'Rédaction',
    travel:           'Voyages',
    dev:              'Code',
    devChat1:         'Refactoriser l\'API Node.js',
    devChat2:         'Déboguer un hook React',
    devChat3:         'Écrire des tests unitaires',
    resChat1:         'Analyse de marché 2025',
    resChat2:         'Panorama de la concurrence',
    writeChat1:       'Article de blog — IA',
    writeChat2:       'Brouillon de newsletter',
    travelChat1:      'Itinéraire Japon',
    codeReviewer:     'Revue de code',
    codeReviewerText: 'Analyse ce code pour détecter les bugs, les problèmes de sécurité et les mauvaises pratiques. Propose des améliorations concrètes avec explications.',
    emailPro:         'Email Pro',
    emailProText:     'Rédige un e-mail professionnel pour le contexte suivant. Sois concis, clair et adopte un ton poli. Signe avec mon prénom.',
    explainSimply:    'Expliquer simplement',
    blogOutline:      'Plan de blog',
    debugHelper:      'Débogueur',
    debugHelperText:  'Voici mon erreur ou comportement inattendu. Aide-moi à diagnostiquer la cause profonde étape par étape, puis suggère une solution.',
  }),

  de: make({
    title:            'Gemini-Gespräche organisieren',
    folderLabel:      '📁 Ordner-Modus',
    promptLabel:      '📝 Prompt-Modus',
    research:         'Recherche',
    writing:          'Schreiben',
    travel:           'Reisen',
    dev:              'Code',
    devChat1:         'Node.js API refaktorieren',
    devChat2:         'React Hook debuggen',
    devChat3:         'Unit-Tests schreiben',
    resChat1:         'Marktanalyse 2025',
    resChat2:         'Wettbewerber-Übersicht',
    writeChat1:       'Blogbeitrag — KI-Tools',
    writeChat2:       'Newsletter-Entwurf',
    travelChat1:      'Japan-Reiseplan',
    codeReviewer:     'Code-Review',
    codeReviewerText: 'Überprüfe den folgenden Code auf Bugs, Sicherheitsprobleme und Best Practices. Schlage konkrete Verbesserungen mit Erklärungen vor.',
    emailPro:         'E-Mail Profi',
    emailProText:     'Verfasse eine professionelle E-Mail für den folgenden Kontext. Sei präzise, klar und höflich im Ton. Beende sie mit meinem Namen.',
    explainSimply:    'Einfach erklären',
    blogOutline:      'Blog-Gliederung',
    debugHelper:      'Debugger',
    debugHelperText:  'Ich habe folgenden Fehler oder unerwartetes Verhalten. Hilf mir, die Grundursache Schritt für Schritt zu diagnostizieren, und schlage dann eine Lösung vor.',
  }),

  es: make({
    title:            'Organiza tus conversaciones de Gemini',
    folderLabel:      '📁 Modo Carpetas',
    promptLabel:      '📝 Modo Prompts',
    research:         'Investigación',
    writing:          'Redacción',
    travel:           'Viajes',
    dev:              'Dev',
    devChat1:         'Refactorizar API Node.js',
    devChat2:         'Depurar hook de React',
    devChat3:         'Escribir pruebas unitarias',
    resChat1:         'Análisis de mercado 2025',
    resChat2:         'Análisis de competidores',
    writeChat1:       'Artículo de blog — IA',
    writeChat2:       'Borrador de newsletter',
    travelChat1:      'Itinerario Japón',
    codeReviewer:     'Revisión de código',
    codeReviewerText: 'Revisa el siguiente código en busca de errores, problemas de seguridad y malas prácticas. Sugiere mejoras concretas con explicaciones.',
    emailPro:         'Email Pro',
    emailProText:     'Redacta un correo electrónico profesional para el siguiente contexto. Sé conciso, claro y usa un tono respetuoso. Firma con mi nombre.',
    explainSimply:    'Explicar fácilmente',
    blogOutline:      'Esquema de blog',
    debugHelper:      'Depurador',
    debugHelperText:  'Tengo el siguiente error o comportamiento inesperado. Ayúdame a diagnosticar la causa raíz paso a paso y luego sugiere una solución.',
  }),

  it: make({
    title:            'Organizza le tue conversazioni Gemini',
    folderLabel:      '📁 Modalità Cartelle',
    promptLabel:      '📝 Modalità Prompt',
    research:         'Ricerca',
    writing:          'Scrittura',
    travel:           'Viaggi',
    dev:              'Dev',
    devChat1:         'Refactoring API Node.js',
    devChat2:         'Debug hook React',
    devChat3:         'Scrivere unit test',
    resChat1:         'Analisi di mercato 2025',
    resChat2:         'Panoramica concorrenti',
    writeChat1:       'Articolo blog — AI',
    writeChat2:       'Bozza newsletter',
    travelChat1:      'Itinerario Giappone',
    codeReviewer:     'Code review',
    codeReviewerText: 'Esamina il seguente codice per bug, problemi di sicurezza e best practice. Suggerisci miglioramenti concreti con spiegazioni.',
    emailPro:         'Email Pro',
    emailProText:     'Scrivi un\'email professionale per il seguente contesto. Sii conciso, chiaro e usa un tono educato. Firma con il mio nome.',
    explainSimply:    'Spiega in modo semplice',
    blogOutline:      'Struttura blog',
    debugHelper:      'Debugger',
    debugHelperText:  'Ho il seguente errore o comportamento inaspettato. Aiutami a diagnosticare la causa radice passo dopo passo, poi suggerisci una soluzione.',
  }),

  pt_BR: make({
    title:            'Organize suas conversas do Gemini',
    folderLabel:      '📁 Modo Pastas',
    promptLabel:      '📝 Modo Prompts',
    research:         'Pesquisa',
    writing:          'Redação',
    travel:           'Viagens',
    dev:              'Dev',
    devChat1:         'Refatorar API Node.js',
    devChat2:         'Depurar hook React',
    devChat3:         'Escrever testes unitários',
    resChat1:         'Análise de mercado 2025',
    resChat2:         'Visão geral dos concorrentes',
    writeChat1:       'Post de blog — IA',
    writeChat2:       'Rascunho de newsletter',
    travelChat1:      'Roteiro pelo Japão',
    codeReviewer:     'Revisão de código',
    codeReviewerText: 'Revise o código a seguir em busca de bugs, problemas de segurança e boas práticas. Sugira melhorias concretas com explicações.',
    emailPro:         'Email Pro',
    emailProText:     'Escreva um e-mail profissional para o seguinte contexto. Seja conciso, claro e use um tom educado. Assine com meu nome.',
    explainSimply:    'Explique de forma simples',
    blogOutline:      'Esboço de blog',
    debugHelper:      'Depurador',
    debugHelperText:  'Tenho o seguinte erro ou comportamento inesperado. Me ajude a diagnosticar a causa raiz passo a passo e depois sugira uma correção.',
  }),

  pt_PT: make({
    title:            'Organize as suas conversas do Gemini',
    folderLabel:      '📁 Modo Pastas',
    promptLabel:      '📝 Modo Prompts',
    research:         'Pesquisa',
    writing:          'Redação',
    travel:           'Viagens',
    dev:              'Dev',
    devChat1:         'Refatorar API Node.js',
    devChat2:         'Depurar hook React',
    devChat3:         'Escrever testes unitários',
    resChat1:         'Análise de mercado 2025',
    resChat2:         'Visão geral dos concorrentes',
    writeChat1:       'Artigo de blog — IA',
    writeChat2:       'Rascunho de newsletter',
    travelChat1:      'Itinerário pelo Japão',
    codeReviewer:     'Revisão de código',
    codeReviewerText: 'Reveja o seguinte código em busca de bugs, problemas de segurança e boas práticas. Sugira melhorias concretas com explicações.',
    emailPro:         'Email Pro',
    emailProText:     'Escreva um e-mail profissional para o seguinte contexto. Seja conciso, claro e use um tom educado. Assine com o meu nome.',
    explainSimply:    'Explique de forma simples',
    blogOutline:      'Esboço de blog',
    debugHelper:      'Depurador',
    debugHelperText:  'Tenho o seguinte erro ou comportamento inesperado. Ajuda-me a diagnosticar a causa raiz passo a passo e depois sugere uma solução.',
  }),

  ru: make({
    title:            'Организуйте беседы в Gemini',
    folderLabel:      '📁 Режим папок',
    promptLabel:      '📝 Режим подсказок',
    research:         'Исследования',
    writing:          'Тексты',
    travel:           'Путешествия',
    dev:              'Разр.',
    devChat1:         'Рефакторинг Node.js API',
    devChat2:         'Отладка хука React',
    devChat3:         'Написать юнит-тесты',
    resChat1:         'Анализ рынка 2025',
    resChat2:         'Обзор конкурентов',
    writeChat1:       'Статья в блог — ИИ',
    writeChat2:       'Черновик рассылки',
    travelChat1:      'Маршрут по Японии',
    codeReviewer:     'Ревью кода',
    codeReviewerText: 'Проверь следующий код на наличие ошибок, уязвимостей безопасности и соответствие лучшим практикам. Предложи конкретные улучшения с объяснениями.',
    emailPro:         'Email Pro',
    emailProText:     'Напиши профессиональное письмо для следующего контекста. Будь кратким, чётким и вежливым в тоне. Подпиши своим именем.',
    explainSimply:    'Объясни просто',
    blogOutline:      'План блога',
    debugHelper:      'Помощник отладки',
    debugHelperText:  'У меня следующая ошибка или неожиданное поведение. Помоги мне шаг за шагом определить первопричину, а затем предложи решение.',
  }),

  pl: make({
    title:            'Organizuj rozmowy w Gemini',
    folderLabel:      '📁 Tryb folderów',
    promptLabel:      '📝 Tryb podpowiedzi',
    research:         'Badania',
    writing:          'Pisanie',
    travel:           'Podróże',
    dev:              'Dev',
    devChat1:         'Refaktoryzacja API Node.js',
    devChat2:         'Debugowanie hooka React',
    devChat3:         'Pisanie testów jednostkowych',
    resChat1:         'Analiza rynku 2025',
    resChat2:         'Przegląd konkurencji',
    writeChat1:       'Post na blogu — AI',
    writeChat2:       'Szkic newslettera',
    travelChat1:      'Plan podróży do Japonii',
    codeReviewer:     'Przegląd kodu',
    codeReviewerText: 'Sprawdź poniższy kod pod kątem błędów, problemów z bezpieczeństwem i dobrych praktyk. Zaproponuj konkretne ulepszenia z wyjaśnieniami.',
    emailPro:         'Email Pro',
    emailProText:     'Napisz profesjonalny e-mail dla następującego kontekstu. Bądź zwięzły, jasny i używaj uprzejmego tonu. Podpisz swoim imieniem.',
    explainSimply:    'Wyjaśnij prosto',
    blogOutline:      'Konspekt bloga',
    debugHelper:      'Debugger',
    debugHelperText:  'Mam następujący błąd lub nieoczekiwane zachowanie. Pomóż mi zdiagnozować przyczynę krok po kroku, a następnie zaproponuj rozwiązanie.',
  }),

  zh_CN: make({
    title:            '整理您的 Gemini 对话',
    folderLabel:      '📁 文件夹模式',
    promptLabel:      '📝 提示词模式',
    research:         '研究',
    writing:          '写作',
    travel:           '旅行',
    dev:              '开发',
    devChat1:         '重构 Node.js API',
    devChat2:         '调试 React Hook',
    devChat3:         '编写单元测试',
    resChat1:         '2025 市场分析',
    resChat2:         '竞争对手概览',
    writeChat1:       '博客文章 — AI 工具',
    writeChat2:       '新闻通讯草稿',
    travelChat1:      '日本行程计划',
    codeReviewer:     '代码审查',
    codeReviewerText: '审查以下代码的错误、安全问题和最佳实践。请提出具体的改进建议并附上说明。',
    emailPro:         '邮件助手',
    emailProText:     '请为以下情境撰写一封专业邮件。要简洁、清晰、语气礼貌，并以我的姓名署名。',
    explainSimply:    '简单解释',
    blogOutline:      '博客提纲',
    debugHelper:      '调试助手',
    debugHelperText:  '我遇到了以下错误或异常行为，请逐步帮我找出根本原因，然后提出修复方案。',
  }),

  ja: make({
    title:            'Gemini の会話を整理しよう',
    folderLabel:      '📁 フォルダモード',
    promptLabel:      '📝 プロンプトモード',
    research:         'リサーチ',
    writing:          '執筆',
    travel:           '旅行',
    dev:              '開発',
    devChat1:         'Node.js API リファクタリング',
    devChat2:         'React Hook デバッグ',
    devChat3:         'ユニットテスト作成',
    resChat1:         '市場分析 2025',
    resChat2:         '競合他社概要',
    writeChat1:       'ブログ記事 — AIツール',
    writeChat2:       'ニュースレター草稿',
    travelChat1:      '日本旅行プラン',
    codeReviewer:     'コードレビュー',
    codeReviewerText: '以下のコードのバグ、セキュリティ問題、ベストプラクティスを確認してください。具体的な改善案を説明付きで提案してください。',
    emailPro:         'メール作成',
    emailProText:     '以下の状況に合わせてプロフェッショナルなメールを書いてください。簡潔で明確に、丁寧な言葉遣いで。最後に私の名前で締めてください。',
    explainSimply:    'わかりやすく説明',
    blogOutline:      'ブログ構成',
    debugHelper:      'デバッグ支援',
    debugHelperText:  '以下のエラーまたは予期しない動作が発生しています。根本原因をステップごとに診断し、修正方法を提案してください。',
  }),

  ko: make({
    title:            'Gemini 대화를 정리하세요',
    folderLabel:      '📁 폴더 모드',
    promptLabel:      '📝 프롬프트 모드',
    research:         '리서치',
    writing:          '글쓰기',
    travel:           '여행',
    dev:              '개발',
    devChat1:         'Node.js API 리팩터링',
    devChat2:         'React Hook 디버깅',
    devChat3:         '단위 테스트 작성',
    resChat1:         '2025 시장 분석',
    resChat2:         '경쟁사 분석',
    writeChat1:       '블로그 포스트 — AI 도구',
    writeChat2:       '뉴스레터 초안',
    travelChat1:      '일본 여행 일정',
    codeReviewer:     '코드 리뷰',
    codeReviewerText: '다음 코드의 버그, 보안 문제, 모범 사례를 검토하세요. 설명과 함께 구체적인 개선 사항을 제안하세요.',
    emailPro:         '이메일 작성',
    emailProText:     '다음 상황에 맞는 전문적인 이메일을 작성하세요. 간결하고 명확하게, 정중한 어조로 작성하고 내 이름으로 마무리하세요.',
    explainSimply:    '쉽게 설명하기',
    blogOutline:      '블로그 개요',
    debugHelper:      '디버그 도우미',
    debugHelperText:  '다음과 같은 오류 또는 예상치 못한 동작이 있습니다. 근본 원인을 단계별로 진단하고 해결 방법을 제안해 주세요.',
  }),

  hi: make({
    title:            'Gemini वार्तालाप व्यवस्थित करें',
    folderLabel:      '📁 फ़ोल्डर मोड',
    promptLabel:      '📝 प्रॉम्प्ट मोड',
    research:         'शोध',
    writing:          'लेखन',
    travel:           'यात्रा',
    dev:              'कोड',
    devChat1:         'Node.js API रीफैक्टर',
    devChat2:         'React Hook डीबग',
    devChat3:         'यूनिट टेस्ट लिखें',
    resChat1:         'बाज़ार विश्लेषण 2025',
    resChat2:         'प्रतिस्पर्धी समीक्षा',
    writeChat1:       'ब्लॉग पोस्ट — AI टूल्स',
    writeChat2:       'न्यूज़लेटर ड्राफ्ट',
    travelChat1:      'जापान यात्रा कार्यक्रम',
    codeReviewer:     'कोड समीक्षा',
    codeReviewerText: 'निम्नलिखित कोड में बग, सुरक्षा समस्याओं और सर्वोत्तम प्रथाओं की जाँच करें। स्पष्टीकरण के साथ ठोस सुधार सुझाएं।',
    emailPro:         'ईमेल सहायक',
    emailProText:     'निम्नलिखित संदर्भ के लिए एक पेशेवर ईमेल लिखें। संक्षिप्त, स्पष्ट और विनम्र रहें। मेरे नाम से समाप्त करें।',
    explainSimply:    'सरलता से समझाएं',
    blogOutline:      'ब्लॉग रूपरेखा',
    debugHelper:      'डीबग सहायक',
    debugHelperText:  'मुझे निम्नलिखित त्रुटि या अप्रत्याशित व्यवहार आ रहा है। कृपया चरण-दर-चरण मूल कारण का निदान करें, फिर एक समाधान सुझाएं।',
  }),

  ro: make({
    title:            'Organizați conversațiile Gemini',
    folderLabel:      '📁 Mod Foldere',
    promptLabel:      '📝 Mod Prompturi',
    research:         'Cercetare',
    writing:          'Scriere',
    travel:           'Călătorii',
    dev:              'Dev',
    devChat1:         'Refactorizare API Node.js',
    devChat2:         'Depanare hook React',
    devChat3:         'Scriere teste unitare',
    resChat1:         'Analiză de piață 2025',
    resChat2:         'Prezentare competitori',
    writeChat1:       'Articol blog — instrumente AI',
    writeChat2:       'Ciornă newsletter',
    travelChat1:      'Itinerar Japonia',
    codeReviewer:     'Revizuire cod',
    codeReviewerText: 'Revizuiește codul următor pentru erori, probleme de securitate și bune practici. Sugerează îmbunătățiri concrete cu explicații.',
    emailPro:         'Email Pro',
    emailProText:     'Scrie un e-mail profesional pentru următorul context. Fii concis, clar și folosește un ton politicos. Semnează cu numele meu.',
    explainSimply:    'Explică simplu',
    blogOutline:      'Structură blog',
    debugHelper:      'Depanator',
    debugHelperText:  'Am următoarea eroare sau comportament neașteptat. Ajută-mă să diagnostichez cauza principală pas cu pas, apoi sugerează o soluție.',
  }),

  sk: make({
    title:            'Organizujte konverzácie v Gemini',
    folderLabel:      '📁 Režim priečinkov',
    promptLabel:      '📝 Režim výziev',
    research:         'Výskum',
    writing:          'Písanie',
    travel:           'Cestovanie',
    dev:              'Vývoj',
    devChat1:         'Refaktorovanie API Node.js',
    devChat2:         'Debugovanie React hooku',
    devChat3:         'Písanie unit testov',
    resChat1:         'Analýza trhu 2025',
    resChat2:         'Prehľad konkurencie',
    writeChat1:       'Blogový príspevok — AI nástroje',
    writeChat2:       'Návrh newslettera',
    travelChat1:      'Plán cesty do Japonska',
    codeReviewer:     'Kontrola kódu',
    codeReviewerText: 'Skontroluj nasledujúci kód na chyby, bezpečnostné problémy a osvedčené postupy. Navrhni konkrétne vylepšenia s vysvetleniami.',
    emailPro:         'Email Pro',
    emailProText:     'Napíš profesionálny e-mail pre nasledujúci kontext. Buď stručný, jasný a zdvorilý v tóne. Podpíš mojím menom.',
    explainSimply:    'Vysvetli jednoducho',
    blogOutline:      'Osnova blogu',
    debugHelper:      'Debugger',
    debugHelperText:  'Mám nasledujúcu chybu alebo neočakávané správanie. Pomôž mi diagnostikovať hlavnú príčinu krok za krokom a potom navrhni opravu.',
  }),

  cs: make({
    title:            'Organizujte konverzace v Gemini',
    folderLabel:      '📁 Režim složek',
    promptLabel:      '📝 Režim výzev',
    research:         'Výzkum',
    writing:          'Psaní',
    travel:           'Cestování',
    dev:              'Vývoj',
    devChat1:         'Refaktorizace API Node.js',
    devChat2:         'Ladění hooku React',
    devChat3:         'Psaní unit testů',
    resChat1:         'Analýza trhu 2025',
    resChat2:         'Přehled konkurence',
    writeChat1:       'Blogový příspěvek — AI nástroje',
    writeChat2:       'Návrh newsletteru',
    travelChat1:      'Itinerář do Japonska',
    codeReviewer:     'Kontrola kódu',
    codeReviewerText: 'Zkontroluj následující kód na chyby, bezpečnostní problémy a osvědčené postupy. Navrhni konkrétní vylepšení s vysvětleními.',
    emailPro:         'Email Pro',
    emailProText:     'Napiš profesionální e-mail pro následující kontext. Buď stručný, jasný a zdvořilý v tónu. Podpiš mým jménem.',
    explainSimply:    'Vysvětli jednoduše',
    blogOutline:      'Osnova blogu',
    debugHelper:      'Debugger',
    debugHelperText:  'Mám následující chybu nebo neočekávané chování. Pomoz mi diagnostikovat hlavní příčinu krok za krokem a pak navrhni opravu.',
  }),

};
