/**
 * Localized sample data for AI Folders store-listing screenshots.
 * Shows conversations from multiple AI services living in the same folders,
 * the prompt library with multi-site injection, and the site-button row.
 */

const NOW = Date.now();
const DAY = 86400000;

function make(locale) {
  const {
    title,
    folderLabel,
    promptLabel,
    folderScreenTitle  = 'All your AI chats, one organized place',
    promptScreenTitle  = 'Your best prompts, ready for any AI',
    mobileScreenTitle  = 'Access your AI chats from your phone',
    contextMenuScreenTitle = 'Save any AI conversation in one right-click',
    ctxMenuSaveLabel   = 'Save to AI Folders',
    ctxBack    = 'Back',
    ctxForward = 'Forward',
    ctxSavePage = 'Save page as…',
    ctxPrint   = 'Print…',
    aiReply    = "Here's a clean refactored version using async/await and proper error handling…",
    sidebarRecent = 'Recent',
    chatInputPlaceholder = 'Ask me anything',
    // Site labels shown in conversation list
    siteGemini     = 'Gemini',
    siteClaude     = 'Claude',
    siteChatGPT    = 'ChatGPT',
    siteCopilot    = 'Copilot',
    sitePerplexity = 'Perplexity',
    syncFolderName = 'AI Folders (Sync)',
    research, writing, travel,
    dev         = 'Dev',
    // Conversation titles (English defaults, represent multi-site use)
    devChat1    = 'Refactor Node.js API',
    devChat2    = 'Debug React hook',
    devChat3    = 'Write unit tests',
    resChat1    = 'Market analysis 2025',
    resChat2    = 'Competitor overview',
    writeChat1  = 'Blog post — AI productivity',
    writeChat2  = 'Newsletter draft',
    travelChat1 = 'Japan trip itinerary',
    // Prompt titles
    codeReviewer, codeReviewerText,
    emailPro,     emailProText,
    explainSimply, blogOutline,
    debugHelper     = 'Debug Helper',
    debugHelperText = 'I have the following error or unexpected behavior. Help me diagnose the root cause step by step, then suggest a fix.',
  } = locale;

  const devFolder = `💻 ${dev}`;
  const resFolder = `🔬 ${research || 'Research'}`;
  const writeFolder = `✍️ ${writing || 'Writing'}`;

  return {
    title,
    folderLabel,
    promptLabel,
    folderScreenTitle,
    promptScreenTitle,
    mobileScreenTitle,
    contextMenuScreenTitle,
    ctxMenuSaveLabel,
    ctxBack, ctxForward, ctxSavePage, ctxPrint,
    aiReply, sidebarRecent, chatInputPlaceholder,
    syncFolderName,
    devChat1, devChat2, resChat1, writeChat1,
    pinnedFolders: [devFolder],
    folders: {
      // Dev folder: conversations from ChatGPT + Claude + Gemini
      [devFolder]: [
        { url: 'https://chatgpt.com/c/aaa1',   title: devChat1,  timestamp: NOW - 1 * DAY, site: 'chatgpt' },
        { url: 'https://claude.ai/chat/aaa2',   title: devChat2,  timestamp: NOW - 2 * DAY, site: 'claude' },
        { url: 'https://chatgpt.com/c/aaa3',    title: devChat3,  timestamp: NOW - 3 * DAY, site: 'chatgpt' },
        { url: 'https://gemini.google.com/app/aaa4', title: `${devChat1} v2`, timestamp: NOW - 4 * DAY, site: 'gemini' },
      ],
      // Research folder: Perplexity + Copilot + Claude
      [resFolder]: [
        { url: 'https://www.perplexity.ai/search/bbb1', title: resChat1, timestamp: NOW - 1 * DAY, site: 'perplexity' },
        { url: 'https://copilot.microsoft.com/c/bbb2',  title: resChat2, timestamp: NOW - 2 * DAY, site: 'copilot' },
        { url: 'https://claude.ai/chat/bbb3',           title: `${resChat1} — deep dive`, timestamp: NOW - 5 * DAY, site: 'claude' },
      ],
      // Writing folder: Gemini + Claude + ChatGPT
      [writeFolder]: [
        { url: 'https://gemini.google.com/app/ccc1', title: writeChat1, timestamp: NOW - 1 * DAY, site: 'gemini' },
        { url: 'https://claude.ai/chat/ccc2',        title: writeChat2, timestamp: NOW - 2 * DAY, site: 'claude' },
        { url: 'https://chatgpt.com/c/ccc3',         title: `${writeChat2} final`, timestamp: NOW - 3 * DAY, site: 'chatgpt' },
      ],
    },
    pinnedPrompts: [codeReviewer || 'Code Reviewer'],
    prompts: {
      [codeReviewer || 'Code Reviewer']: {
        text: codeReviewerText || 'Review this code for correctness, performance, and readability. Point out any bugs, anti-patterns, or style issues. Suggest concrete improvements.',
        timestamp: NOW - 3 * DAY,
        pinned: true,
      },
      [emailPro || 'Email Pro']: {
        text: emailProText || 'Rewrite the following email to be professional, concise, and clear. Keep the core message but improve the tone and structure.',
        timestamp: NOW - 5 * DAY,
      },
      [explainSimply || 'Explain Simply']: {
        text: 'Explain the following concept as if I were a smart 12-year-old. Use simple language, a real-world analogy, and one concrete example.',
        timestamp: NOW - 7 * DAY,
      },
      [debugHelper]: {
        text: debugHelperText,
        timestamp: NOW - 10 * DAY,
      },
      [blogOutline || 'Blog Outline']: {
        text: 'Create a detailed blog post outline on the following topic. Include an engaging title, introduction hook, 5 main sections with sub-points, and a conclusion with a call to action.',
        timestamp: NOW - 14 * DAY,
      },
    },
  };
}

// ─── Locale definitions ───────────────────────────────────────────────────────

const LOCALES = {
  en: make({ title: 'Organize your AI conversations', folderLabel: '📁 Folder Mode', promptLabel: '📝 Prompt Mode',
    dev: 'Dev', research: 'Research', writing: 'Writing',
    ctxMenuSaveLabel: 'Save to AI Folders', syncFolderName: 'AI Folders (Sync)',
    aiReply: "Here's a clean refactored version using async/await and proper error handling…",
    sidebarRecent: 'Recent',
    chatInputPlaceholder: 'Ask me anything',
    devChat1: 'Refactor Node.js API', devChat2: 'Debug React hook', devChat3: 'Write unit tests',
    resChat1: 'Market analysis 2025', resChat2: 'Competitor overview',
    writeChat1: 'Blog post — AI productivity', writeChat2: 'Newsletter draft',
    codeReviewer: 'Code Reviewer', codeReviewerText: 'Review this code for correctness, performance, and readability. Point out any bugs, anti-patterns, or style issues. Suggest concrete improvements.',
    emailPro: 'Email Pro', emailProText: 'Rewrite the following email to be professional, concise, and clear.',
    explainSimply: 'Explain Simply', blogOutline: 'Blog Outline',
  }),

  fr: make({ title: 'Organisez vos conversations IA', folderLabel: '📁 Mode Dossiers', promptLabel: '📝 Mode Prompts',
    dev: 'Dev', research: 'Recherche', writing: 'Rédaction',
    ctxMenuSaveLabel: 'Sauvegarder dans Dossiers IA', syncFolderName: 'Dossiers IA (Sync)',
    aiReply: 'Voici une version refactorisée propre avec async/await et une gestion des erreurs…',
    sidebarRecent: 'Récentes',
    chatInputPlaceholder: 'Demandez ce que vous voulez',
    ctxBack: 'Retour', ctxForward: 'Suivant', ctxSavePage: 'Enregistrer sous…', ctxPrint: 'Imprimer…',
    devChat1: 'Refactoriser l\'API Node.js', devChat2: 'Déboguer le hook React', devChat3: 'Écrire des tests unitaires',
    resChat1: 'Analyse de marché 2025', resChat2: 'Vue d\'ensemble concurrents',
    writeChat1: 'Article de blog — IA productive', writeChat2: 'Brouillon newsletter',
    codeReviewer: 'Relecteur de Code', codeReviewerText: 'Analyse ce code pour détecter les bugs, les problèmes de sécurité et les mauvaises pratiques. Propose des améliorations concrètes avec explications.',
    emailPro: 'Email Pro', emailProText: 'Rédige un e-mail professionnel pour le contexte suivant. Sois concis, clair et adopte un ton poli. Signe avec mon prénom.',
    explainSimply: 'Expliquer simplement', blogOutline: 'Plan de blog',
    debugHelper: 'Débogueur', debugHelperText: 'Voici mon erreur ou comportement inattendu. Aide-moi à diagnostiquer la cause profonde étape par étape, puis suggère une solution.',
    folderScreenTitle: 'Tous vos chats IA, un espace organisé',
    promptScreenTitle: 'Vos meilleurs prompts, prêts pour toute IA',
    mobileScreenTitle: 'Accédez à vos chats IA depuis votre téléphone',
    contextMenuScreenTitle: 'Sauvegardez une conversation IA en un clic droit',
  }),

  de: make({ title: 'KI-Gespräche organisieren', folderLabel: '📁 Ordner-Modus', promptLabel: '📝 Prompt-Modus',
    dev: 'Entwicklung', research: 'Recherche', writing: 'Texte',
    ctxMenuSaveLabel: 'In KI-Ordner speichern', syncFolderName: 'KI-Ordner (Sync)',
    aiReply: 'Hier ist eine saubere Refaktorierung mit async/await und ordentlicher Fehlerbehandlung…',
    sidebarRecent: 'Letzte',
    chatInputPlaceholder: 'Stellen Sie Ihre Frage',
    ctxBack: 'Zurück', ctxForward: 'Vor', ctxSavePage: 'Seite speichern unter…', ctxPrint: 'Drucken…',
    devChat1: 'Node.js-API refaktorieren', devChat2: 'React-Hook debuggen', devChat3: 'Unit-Tests schreiben',
    resChat1: 'Marktanalyse 2025', resChat2: 'Wettbewerbsübersicht',
    writeChat1: 'Blogartikel — KI-Produktivität', writeChat2: 'Newsletter-Entwurf',
    codeReviewer: 'Code-Reviewer', codeReviewerText: 'Überprüfe den folgenden Code auf Bugs, Sicherheitsprobleme und Best Practices. Schlage konkrete Verbesserungen mit Erklärungen vor.',
    emailPro: 'E-Mail Profi', emailProText: 'Verfasse eine professionelle E-Mail für den folgenden Kontext. Sei präzise, klar und höflich im Ton. Beende sie mit meinem Namen.',
    explainSimply: 'Einfach erklären', blogOutline: 'Blog-Gliederung',
    debugHelper: 'Debugger', debugHelperText: 'Ich habe folgenden Fehler oder unerwartetes Verhalten. Hilf mir, die Grundursache Schritt für Schritt zu diagnostizieren, und schlage dann eine Lösung vor.',
    folderScreenTitle: 'Alle KI-Chats, ein organisierter Ort',
    promptScreenTitle: 'Ihre besten Prompts, bereit für jede KI',
    mobileScreenTitle: 'KI-Chats auch auf dem Handy',
    contextMenuScreenTitle: 'KI-Gespräch per Rechtsklick speichern',
  }),

  es: make({ title: 'Organiza tus conversaciones de IA', folderLabel: '📁 Modo Carpetas', promptLabel: '📝 Modo Prompts',
    dev: 'Desarrollo', research: 'Investigación', writing: 'Escritura',
    ctxMenuSaveLabel: 'Guardar en Carpetas IA', syncFolderName: 'Carpetas IA (Sync)',
    aiReply: 'Aquí tienes una versión refactorizada usando async/await y manejo adecuado de errores…',
    sidebarRecent: 'Recientes',
    chatInputPlaceholder: 'Pregunta lo que quieras',
    ctxBack: 'Atrás', ctxForward: 'Adelante', ctxSavePage: 'Guardar como…', ctxPrint: 'Imprimir…',
    devChat1: 'Refactorizar API Node.js', devChat2: 'Depurar hook React', devChat3: 'Escribir pruebas unitarias',
    resChat1: 'Análisis de mercado 2025', resChat2: 'Visión general competidores',
    writeChat1: 'Post blog — productividad IA', writeChat2: 'Borrador newsletter',
    codeReviewer: 'Revisor de Código', codeReviewerText: 'Revisa el siguiente código en busca de errores, problemas de seguridad y malas prácticas. Sugiere mejoras concretas con explicaciones.',
    emailPro: 'Email Pro', emailProText: 'Redacta un correo electrónico profesional para el siguiente contexto. Sé conciso, claro y usa un tono respetuoso. Firma con mi nombre.',
    explainSimply: 'Explicar fácilmente', blogOutline: 'Esquema de blog',
    debugHelper: 'Depurador', debugHelperText: 'Tengo el siguiente error o comportamiento inesperado. Ayúdame a diagnosticar la causa raíz paso a paso y luego sugiere una solución.',
    folderScreenTitle: 'Todos tus chats IA, un lugar organizado',
    promptScreenTitle: 'Tus mejores prompts, listos para cualquier IA',
    mobileScreenTitle: 'Accede a tus chats IA desde el móvil',
    contextMenuScreenTitle: 'Guarda una conversación IA con un clic derecho',
  }),

  it: make({ title: 'Organizza le tue conversazioni IA', folderLabel: '📁 Modalità Cartelle', promptLabel: '📝 Modalità Prompt',
    dev: 'Dev', research: 'Ricerca', writing: 'Scrittura',
    ctxMenuSaveLabel: 'Salva in Cartelle IA', syncFolderName: 'Cartelle IA (Sync)',
    aiReply: 'Ecco una versione refactored pulita con async/await e gestione degli errori…',
    sidebarRecent: 'Recenti',
    chatInputPlaceholder: 'Chiedi quello che vuoi',
    ctxBack: 'Indietro', ctxForward: 'Avanti', ctxSavePage: 'Salva pagina come…', ctxPrint: 'Stampa…',
    devChat1: 'Refactoring API Node.js', devChat2: 'Debug hook React', devChat3: 'Scrivere test unitari',
    resChat1: 'Analisi di mercato 2025', resChat2: 'Panoramica concorrenti',
    writeChat1: 'Post blog — produttività IA', writeChat2: 'Bozza newsletter',
    codeReviewer: 'Revisore Codice', codeReviewerText: 'Esamina il seguente codice per bug, problemi di sicurezza e best practice. Suggerisci miglioramenti concreti con spiegazioni.',
    emailPro: 'Email Pro', emailProText: 'Scrivi un\'email professionale per il seguente contesto. Sii conciso, chiaro e usa un tono educato. Firma con il mio nome.',
    explainSimply: 'Spiega in modo semplice', blogOutline: 'Struttura blog',
    debugHelper: 'Debugger', debugHelperText: 'Ho il seguente errore o comportamento inaspettato. Aiutami a diagnosticare la causa radice passo dopo passo, poi suggerisci una soluzione.',
    folderScreenTitle: 'Tutte le chat IA, un posto organizzato',
    promptScreenTitle: 'I tuoi migliori prompt, pronti per ogni IA',
    mobileScreenTitle: 'Accedi alle tue chat IA dal telefono',
    contextMenuScreenTitle: 'Salva una conversazione IA con un clic destro',
  }),

  pt_BR: make({ title: 'Organize suas conversas de IA', folderLabel: '📁 Modo Pastas', promptLabel: '📝 Modo Prompts',
    dev: 'Dev', research: 'Pesquisa', writing: 'Escrita',
    ctxMenuSaveLabel: 'Salvar em Pastas IA', syncFolderName: 'Pastas IA (Sync)',
    aiReply: 'Aqui está uma versão refatorada usando async/await e tratamento de erros adequado…',
    sidebarRecent: 'Recentes',
    chatInputPlaceholder: 'Pergunte o que quiser',
    ctxBack: 'Voltar', ctxForward: 'Avançar', ctxSavePage: 'Salvar página como…', ctxPrint: 'Imprimir…',
    devChat1: 'Refatorar API Node.js', devChat2: 'Depurar hook React', devChat3: 'Escrever testes unitários',
    resChat1: 'Análise de mercado 2025', resChat2: 'Visão geral dos concorrentes',
    writeChat1: 'Post blog — produtividade IA', writeChat2: 'Rascunho newsletter',
    codeReviewer: 'Revisor de Código', codeReviewerText: 'Revise o código a seguir em busca de bugs, problemas de segurança e boas práticas. Sugira melhorias concretas com explicações.',
    emailPro: 'Email Pro', emailProText: 'Escreva um e-mail profissional para o seguinte contexto. Seja conciso, claro e use um tom educado. Assine com meu nome.',
    explainSimply: 'Explique de forma simples', blogOutline: 'Esboço de blog',
    debugHelper: 'Depurador', debugHelperText: 'Tenho o seguinte erro ou comportamento inesperado. Me ajude a diagnosticar a causa raiz passo a passo e depois sugira uma correção.',
    folderScreenTitle: 'Todos os seus chats IA, num só lugar',
    promptScreenTitle: 'Seus melhores prompts, prontos para qualquer IA',
    mobileScreenTitle: 'Acesse seus chats IA pelo celular',
    contextMenuScreenTitle: 'Salve uma conversa IA com um clique direito',
  }),

  pt_PT: make({ title: 'Organize as suas conversas de IA', folderLabel: '📁 Modo Pastas', promptLabel: '📝 Modo Prompts',
    dev: 'Dev', research: 'Pesquisa', writing: 'Redação',
    ctxMenuSaveLabel: 'Guardar nas Pastas IA', syncFolderName: 'Pastas IA (Sync)',
    aiReply: 'Aqui está uma versão refatorada limpa com async/await e tratamento de erros…',
    sidebarRecent: 'Recentes',
    chatInputPlaceholder: 'Pergunte o que quiser',
    ctxBack: 'Recuar', ctxForward: 'Avançar', ctxSavePage: 'Guardar página como…', ctxPrint: 'Imprimir…',
    devChat1: 'Refatorar API Node.js', devChat2: 'Depurar hook React', devChat3: 'Escrever testes unitários',
    resChat1: 'Análise de mercado 2025', resChat2: 'Visão geral dos concorrentes',
    writeChat1: 'Artigo de blog — IA', writeChat2: 'Rascunho de newsletter',
    codeReviewer: 'Revisão de código', codeReviewerText: 'Reveja o seguinte código em busca de bugs, problemas de segurança e boas práticas. Sugira melhorias concretas com explicações.',
    emailPro: 'Email Pro', emailProText: 'Escreva um e-mail profissional para o seguinte contexto. Seja conciso, claro e use um tom educado. Assine com o meu nome.',
    explainSimply: 'Explique de forma simples', blogOutline: 'Esboço de blog',
    debugHelper: 'Depurador', debugHelperText: 'Tenho o seguinte erro ou comportamento inesperado. Ajuda-me a diagnosticar a causa raiz passo a passo e depois sugere uma solução.',
    folderScreenTitle: 'Todos os seus chats IA, num só lugar organizado',
    promptScreenTitle: 'Os seus melhores prompts, prontos para qualquer IA',
    mobileScreenTitle: 'Aceda aos seus chats IA no telemóvel',
    contextMenuScreenTitle: 'Guarde conversas IA com um clique direito',
  }),

  ru: make({ title: 'Организуйте беседы с ИИ', folderLabel: '📁 Режим папок', promptLabel: '📝 Режим промптов',
    dev: 'Разработка', research: 'Исследования', writing: 'Тексты',
    ctxMenuSaveLabel: 'Сохранить в ИИ-папки', syncFolderName: 'ИИ-папки (Sync)',
    aiReply: 'Вот чистая рефакторинговая версия с async/await и правильной обработкой ошибок…',
    sidebarRecent: 'Последние',
    chatInputPlaceholder: 'Задайте любой вопрос',
    ctxBack: 'Nazad', ctxForward: 'Вперёд', ctxSavePage: 'Сохранить страницу как…', ctxPrint: 'Печать…',
    devChat1: 'Рефакторинг Node.js API', devChat2: 'Отладка React-хука', devChat3: 'Написать юнит-тесты',
    resChat1: 'Анализ рынка 2025', resChat2: 'Обзор конкурентов',
    writeChat1: 'Статья блога — продуктивность с ИИ', writeChat2: 'Черновик рассылки',
    codeReviewer: 'Ревью кода', codeReviewerText: 'Проверь следующий код на наличие ошибок, уязвимостей безопасности и соответствие лучшим практикам. Предложи конкретные улучшения с объяснениями.',
    emailPro: 'Email Pro', emailProText: 'Напиши профессиональное письмо для следующего контекста. Будь кратким, чётким и вежливым в тоне. Подпиши своим именем.',
    explainSimply: 'Объясни просто', blogOutline: 'План блога',
    debugHelper: 'Помощник отладки', debugHelperText: 'У меня следующая ошибка или неожиданное поведение. Помоги мне шаг за шагом определить первопричину, а затем предложи решение.',
    folderScreenTitle: 'Все чаты ИИ — одно упорядоченное место',
    promptScreenTitle: 'Ваши лучшие промпты — для любого ИИ',
    mobileScreenTitle: 'Открывайте чаты ИИ с телефона',
    contextMenuScreenTitle: 'Сохраните беседу ИИ одним правым кликом',
  }),

  pl: make({ title: 'Organizuj rozmowy z AI', folderLabel: '📁 Tryb folderów', promptLabel: '📝 Tryb promptów',
    dev: 'Dev', research: 'Badania', writing: 'Pisanie',
    ctxMenuSaveLabel: 'Zapisz w Folderach AI', syncFolderName: 'Foldery AI (Sync)',
    aiReply: 'Oto zrefaktoryzowana wersja z async/await i obsługą błędów…',
    sidebarRecent: 'Ostatnie',
    chatInputPlaceholder: 'Zapytaj o cokolwiek',
    ctxBack: 'Wstecz', ctxForward: 'Dalej', ctxSavePage: 'Zapisz stronę jako…', ctxPrint: 'Drukuj…',
    devChat1: 'Refaktoryzacja API Node.js', devChat2: 'Debugowanie hooka React', devChat3: 'Pisanie testów jednostkowych',
    resChat1: 'Analiza rynku 2025', resChat2: 'Przegląd konkurencji',
    writeChat1: 'Post na blogu — AI', writeChat2: 'Szkic newslettera',
    codeReviewer: 'Przegląd kodu', codeReviewerText: 'Sprawdź poniższy kod pod kątem błędów, problemów z bezpieczeństwem i dobrych praktyk. Zaproponuj konkretne ulepszenia z wyjaśnieniami.',
    emailPro: 'Email Pro', emailProText: 'Napisz profesjonalny e-mail dla następującego kontekstu. Bądź zwięzły, jasny i używaj uprzejmego tonu. Podpisz swoim imieniem.',
    explainSimply: 'Wyjaśnij prosto', blogOutline: 'Konspekt bloga',
    debugHelper: 'Debugger', debugHelperText: 'Mam następujący błąd lub nieoczekiwane zachowanie. Pomóż mi zdiagnozować przyczynę krok po kroku, a następnie zaproponuj rozwiązanie.',
    folderScreenTitle: 'Wszystkie czaty AI w jednym miejscu',
    promptScreenTitle: 'Twoje najlepsze prompty gotowe na każde AI',
    mobileScreenTitle: 'Przeglądaj rozmowy AI z telefonu',
    contextMenuScreenTitle: 'Zapisz rozmowę AI jednym prawym kliknięciem',
  }),

  zh_CN: make({ title: '整理您的 AI 对话', folderLabel: '📁 文件夹模式', promptLabel: '📝 提示词模式',
    dev: '开发', research: '研究', writing: '写作',
    ctxMenuSaveLabel: '保存到 AI 文件夹', syncFolderName: 'AI 文件夹 (同步)',
    aiReply: '这是使用 async/await 的重构版本，包含完善的错误处理…',
    sidebarRecent: '最近',
    chatInputPlaceholder: '问我任何问题',
    ctxBack: '返回', ctxForward: '前进', ctxSavePage: '将网页另存为…', ctxPrint: '打印…',
    devChat1: '重构 Node.js API', devChat2: '调试 React Hook', devChat3: '编写单元测试',
    resChat1: '市场分析 2025', resChat2: '竞争对手概述',
    writeChat1: '博客文章 — AI 生产力', writeChat2: '简报草稿',
    codeReviewer: '代码审查', codeReviewerText: '审查以下代码的错误、安全问题和最佳实践。请提出具体的改进建议并附上说明。',
    emailPro: '邮件助手', emailProText: '请为以下情境撰写一封专业邮件。要简洁、清晰、语气礼貌，并以我的姓名署名。',
    explainSimply: '简单解释', blogOutline: '博客提纲',
    debugHelper: '调试助手', debugHelperText: '我遇到了以下错误或异常行为，请逐步帮我找出根本原因，然后提出修复方案。',
    folderScreenTitle: '所有 AI 对话，一个有序的地方',
    promptScreenTitle: '您的最佳提示词，随时可用于任何 AI',
    mobileScreenTitle: '从手机访问您的 AI 对话',
    contextMenuScreenTitle: '右键一键保存任意 AI 对话',
  }),

  ja: make({ title: 'AI の会話を整理しよう', folderLabel: '📁 フォルダモード', promptLabel: '📝 プロンプトモード',
    dev: '開発', research: 'リサーチ', writing: 'ライティング',
    ctxMenuSaveLabel: 'AI フォルダに保存', syncFolderName: 'AI フォルダ (同期)',
    aiReply: 'async/await を使ったクリーンなリファクタリング例と適切なエラー処理です…',
    sidebarRecent: '最近',
    chatInputPlaceholder: 'なんでも聞いてください',
    ctxBack: '戻る', ctxForward: '進む', ctxSavePage: '名前を付けてページを保存…', ctxPrint: '印刷…',
    devChat1: 'Node.js API リファクタリング', devChat2: 'React フックのデバッグ', devChat3: '単体テストを書く',
    resChat1: '市場分析 2025', resChat2: '競合他社概要',
    writeChat1: 'ブログ記事 — AI 生産性', writeChat2: 'ニュースレター下書き',
    codeReviewer: 'コードレビュアー', codeReviewerText: '以下のコードのバグ、セキュリティ問題、ベストプラクティスを確認してください。具体的な改善案を説明付きで提案してください。',
    emailPro: 'メール作成', emailProText: '以下の状況に合わせてプロフェッショナルなメールを書いてください。簡潔で明確に、丁寧な言葉遣いで。最後に私の名前で締めてください。',
    explainSimply: 'わかりやすく説明', blogOutline: 'ブログ構成',
    debugHelper: 'デバッグ支援', debugHelperText: '以下のエラーまたは予期しない動作が発生しています。根本原因をステップごとに診断し、修正方法を提案してください。',
    folderScreenTitle: 'すべての AI チャットを一箇所に整理',
    promptScreenTitle: 'あなたのベストプロンプトをどの AI にも',
    mobileScreenTitle: 'スマホからも AI チャットにアクセス',
    contextMenuScreenTitle: '右クリック一発で AI 会話を保存',
  }),

  ko: make({ title: 'AI 대화를 정리하세요', folderLabel: '📁 폴더 모드', promptLabel: '📝 프롬프트 모드',
    dev: '개발', research: '연구', writing: '글쓰기',
    ctxMenuSaveLabel: 'AI 폴더에 저장', syncFolderName: 'AI 폴더 (동기화)',
    aiReply: 'async/await를 사용한 리팩터링된 버전과 오류 처리입니다…',
    sidebarRecent: '최근',
    chatInputPlaceholder: '무엇이든 물어보세요',
    ctxBack: '뒤로', ctxForward: '앞으로', ctxSavePage: '다른 이름으로 저장…', ctxPrint: '인쇄…',
    devChat1: 'Node.js API 리팩터링', devChat2: 'React 훅 디버깅', devChat3: '단위 테스트 작성',
    resChat1: '시장 분석 2025', resChat2: '경쟁사 개요',
    writeChat1: '블로그 포스트 — AI 생산성', writeChat2: '뉴스레터 초안',
    codeReviewer: '코드 리뷰어', codeReviewerText: '다음 코드의 버그, 보안 문제, 모범 사례를 검토하세요. 설명과 함께 구체적인 개선 사항을 제안하세요.',
    emailPro: '이메일 작성', emailProText: '다음 상황에 맞는 전문적인 이메일을 작성하세요. 간결하고 명확하게, 정중한 어조로 작성하고 내 이름으로 마무리하세요.',
    explainSimply: '쉽게 설명하기', blogOutline: '블로그 개요',
    debugHelper: '디버그 도우미', debugHelperText: '다음과 같은 오류 또는 예상치 못한 동작이 있습니다. 근본 원인을 단계별로 진단하고 해결 방법을 제안해 주세요.',
    folderScreenTitle: '모든 AI 채팅, 하나의 정리된 공간',
    promptScreenTitle: '최고의 프롬프트, 모든 AI에 바로 사용',
    mobileScreenTitle: '휴대폰에서도 AI 채팅에 접근',
    contextMenuScreenTitle: '우클릭 한 번으로 AI 대화 저장',
  }),

  hi: make({ title: 'AI वार्तालाप व्यवस्थित करें', folderLabel: '📁 फ़ोल्डर मोड', promptLabel: '📝 प्रॉम्प्ट मोड',
    dev: 'कोड', research: 'शोध', writing: 'लेखन',
    ctxMenuSaveLabel: 'AI फ़ोल्डर में सहेजें', syncFolderName: 'AI फ़ोल्डर (Sync)',
    aiReply: 'async/await का उपयोग करके रिफैक्टर्ड कोड और एरर हैंडलिंग यहाँ है…',
    sidebarRecent: 'हाल का',
    chatInputPlaceholder: 'कुछ भी पूछें',
    ctxBack: 'वापस जाएं', ctxForward: 'आगे जाएं', ctxSavePage: 'पेज सेव करें…', ctxPrint: 'प्रिंट करें…',
    devChat1: 'Node.js API रीफैक्टर', devChat2: 'React Hook डीबग', devChat3: 'यूनिट टेस्ट लिखें',
    resChat1: 'बाज़ार विश्लेषण 2025', resChat2: 'प्रतिस्पर्धी समीक्षा',
    writeChat1: 'ब्लॉग पोस्ट — AI टूल्स', writeChat2: 'न्यूज़लेटर ड्राफ्ट',
    codeReviewer: 'कोड समीक्षा', codeReviewerText: 'निम्नलिखित कोड में बग, सुरक्षा समस्याओं और सर्वोत्तम प्रथाओं की जाँच करें। स्पष्टीकरण के साथ ठोस सुधार सुझाएं।',
    emailPro: 'ईमेल सहायक', emailProText: 'निम्नलिखित संदर्भ के लिए एक पेशेवर ईमेल लिखें। संक्षिप्त, स्पष्ट और विनम्र रहें। मेरे नाम से समाप्त करें।',
    explainSimply: 'सरलता से समझाएं', blogOutline: 'ब्लॉग रूपरेखा',
    debugHelper: 'डीबग सहायक', debugHelperText: 'मुझे निम्नलिखित त्रुटि या अप्रत्याशित व्यवहार आ रहा है। कृपया चरण-दर-चरण मूल कारण का निदान करें, फिर एक समाधान सुझाएं।',
    folderScreenTitle: 'सभी AI चैट, एक व्यवस्थित स्थान पर',
    promptScreenTitle: 'आपके बेहतरीन प्रॉम्प्ट, किसी भी AI के लिए तैयार',
    mobileScreenTitle: 'अपने फ़ोन से AI चैट एक्सेस करें',
    contextMenuScreenTitle: 'एक राइट-क्लिक में AI बातचीत सेव करें',
  }),

  ro: make({ title: 'Organizați conversațiile IA', folderLabel: '📁 Mod Foldere', promptLabel: '📝 Mod Prompturi',
    dev: 'Dev', research: 'Cercetare', writing: 'Scriere',
    ctxMenuSaveLabel: 'Salvează în Dosare IA', syncFolderName: 'Dosare IA (Sync)',
    aiReply: 'Iată o versiune refactorizată curată cu async/await și gestionarea erorilor…',
    sidebarRecent: 'Recente',
    chatInputPlaceholder: 'Întrebați orice',
    ctxBack: 'Înapoi', ctxForward: 'Înainte', ctxSavePage: 'Salvați pagina ca…', ctxPrint: 'Imprimați…',
    devChat1: 'Refactorizare API Node.js', devChat2: 'Depanare hook React', devChat3: 'Scriere teste unitare',
    resChat1: 'Analiză de piață 2025', resChat2: 'Prezentare competitori',
    writeChat1: 'Articol blog — instrumente IA', writeChat2: 'Ciornă newsletter',
    codeReviewer: 'Revizuire cod', codeReviewerText: 'Revizuiește codul următor pentru erori, probleme de securitate și bune practici. Sugerează îmbunătățiri concrete cu explicații.',
    emailPro: 'Email Pro', emailProText: 'Scrie un e-mail profesional pentru următorul context. Fii concis, clar și folosește un ton politicos. Semnează cu numele meu.',
    explainSimply: 'Explică simplu', blogOutline: 'Structură blog',
    debugHelper: 'Depanator', debugHelperText: 'Am următoarea eroare sau comportament neașteptat. Ajută-mă să diagnostichez cauza principală pas cu pas, apoi sugerează o soluție.',
    folderScreenTitle: 'Toate chaturile IA, un singur loc organizat',
    promptScreenTitle: 'Cele mai bune prompturi, gata pentru orice IA',
    mobileScreenTitle: 'Accesați chaturile IA de pe telefon',
    contextMenuScreenTitle: 'Salvați orice conversație IA cu un clic dreapta',
  }),

  sk: make({ title: 'Organizujte konverzácie s AI', folderLabel: '📁 Režim priečinkov', promptLabel: '📝 Režim promptov',
    dev: 'Vývoj', research: 'Výskum', writing: 'Písanie',
    ctxMenuSaveLabel: 'Uložiť do AI priečinkov', syncFolderName: 'AI priečinky (Sync)',
    aiReply: 'Tu je čistá refaktorovaná verzia s async/await a spracovaním chýb…',
    sidebarRecent: 'Nedávne',
    chatInputPlaceholder: 'Opýtajte sa čokoľvek',
    ctxBack: 'Späť', ctxForward: 'Dopredu', ctxSavePage: 'Uložiť stránku ako…', ctxPrint: 'Tlačiť…',
    devChat1: 'Refaktorovanie API Node.js', devChat2: 'Debugovanie React hooku', devChat3: 'Písanie unit testov',
    resChat1: 'Analýza trhu 2025', resChat2: 'Prehľad konkurencie',
    writeChat1: 'Blogový príspevok — AI nástroje', writeChat2: 'Návrh newslettera',
    codeReviewer: 'Kontrola kódu', codeReviewerText: 'Skontroluj nasledujúci kód na chyby, bezpečnostné problémy a osvedčené postupy. Navrhni konkrétne vylepšenia s vysvetleniami.',
    emailPro: 'Email Pro', emailProText: 'Napíš profesionálny e-mail pre nasledujúci kontext. Buď stručný, jasný a zdvorilý v tóne. Podpíš mojím menom.',
    explainSimply: 'Vysvetli jednoducho', blogOutline: 'Osnova blogu',
    debugHelper: 'Debugger', debugHelperText: 'Mám nasledujúcu chybu alebo neočakávané správanie. Pomôž mi diagnostikovať hlavnú príčinu krok za krokom a potom navrhni opravu.',
    folderScreenTitle: 'Všetky AI chaty na jednom organizovanom mieste',
    promptScreenTitle: 'Vaše najlepšie prompty pre každé AI',
    mobileScreenTitle: 'Prístup k AI chatom z telefónu',
    contextMenuScreenTitle: 'Uložte AI konverzáciu jedným pravým kliknutím',
  }),

  cs: make({ title: 'Organizujte konverzace s AI', folderLabel: '📁 Režim složek', promptLabel: '📝 Režim promptů',
    dev: 'Vývoj', research: 'Výzkum', writing: 'Psaní',
    ctxMenuSaveLabel: 'Uložit do AI složek', syncFolderName: 'AI složky (Sync)',
    aiReply: 'Zde je čistá refaktorovaná verze s async/await a zpracováním chyb…',
    sidebarRecent: 'Nedávné',
    chatInputPlaceholder: 'Zeptejte se na cokoliv',
    ctxBack: 'Zpět', ctxForward: 'Vpřed', ctxSavePage: 'Uložit stránku jako…', ctxPrint: 'Tisk…',
    devChat1: 'Refaktorizace API Node.js', devChat2: 'Ladění hooku React', devChat3: 'Psaní unit testů',
    resChat1: 'Analýza trhu 2025', resChat2: 'Přehled konkurence',
    writeChat1: 'Blogový příspěvek — AI nástroje', writeChat2: 'Návrh newsletteru',
    codeReviewer: 'Kontrola kódu', codeReviewerText: 'Zkontroluj následující kód na chyby, bezpečnostní problémy a osvědčené postupy. Navrhni konkrétní vylepšení s vysvětleními.',
    emailPro: 'Email Pro', emailProText: 'Napiš profesionální e-mail pro následující kontext. Buď stručný, jasný a zdvořilý v tónu. Podpiš mým jménem.',
    explainSimply: 'Vysvětli jednoduše', blogOutline: 'Osnova blogu',
    debugHelper: 'Debugger', debugHelperText: 'Mám následující chybu nebo neočekávané chování. Pomoz mi diagnostikovat hlavní příčinu krok za krokem a pak navrhni opravu.',
    folderScreenTitle: 'Všechny AI chaty na jednom místě',
    promptScreenTitle: 'Vaše nejlepší výzvy pro každé AI',
    mobileScreenTitle: 'Přístup k AI chatům z telefonu',
    contextMenuScreenTitle: 'Uložte AI konverzaci jedním pravým kliknutím',
  }),

  tr: make({ title: 'YZ konuşmalarınızı düzenleyin', folderLabel: '📁 Klasör Modu', promptLabel: '📝 İstem Modu',
    dev: 'Geliştirme', research: 'Araştırma', writing: 'Yazım',
    ctxMenuSaveLabel: "YZ Klasörleri'ne Kaydet", syncFolderName: 'YZ Klasörleri (Sync)',
    aiReply: 'async/await ve uygun hata yönetimi kullanılarak yazılmış temiz bir yeniden düzenlenmiş sürüm…',
    sidebarRecent: 'Son',
    chatInputPlaceholder: 'İstediğinizi sorun',
    ctxBack: 'Geri', ctxForward: 'İleri', ctxSavePage: 'Sayfayı farklı kaydet…', ctxPrint: 'Yazdır…',
    devChat1: 'Node.js API Refaktöre Et', devChat2: 'React Hook Hata Ayıkla', devChat3: 'Birim Testleri Yaz',
    resChat1: 'Pazar Analizi 2025', resChat2: 'Rekabetçi Genel Bakış',
    writeChat1: 'Blog Yazısı — YZ Verimliliği', writeChat2: 'Bülten Taslağı',
    codeReviewer: 'Kod İnceleme', codeReviewerText: 'Aşağıdaki kodu hatalar, güvenlik sorunları ve en iyi uygulamalar açısından inceleyin. Açıklamalarla birlikte somut iyileştirmeler önerin.',
    emailPro: 'E-posta Uzmanı', emailProText: 'Aşağıdaki bağlam için profesyonel bir e-posta yazın. Kısa, net ve kibarca bir tonla yazın. Adımla imzalayın.',
    explainSimply: 'Basitçe Açıkla', blogOutline: 'Blog Taslağı',
    debugHelper: 'Hata Ayıklama Yardımcısı', debugHelperText: 'Aşağıdaki hata veya beklenmedik davranışa sahibim. Kök nedeni adım adım teşhis etmeme yardımcı olun, ardından bir düzeltme önerin.',
    folderScreenTitle: 'Tüm YZ sohbetleriniz, düzenli bir yerde',
    promptScreenTitle: 'En iyi istemleriniz, her yapay zeka için hazır',
    mobileScreenTitle: 'YZ sohbetlerinize telefonunuzdan erişin',
    contextMenuScreenTitle: 'Herhangi bir YZ konuşmasını tek sağ tıkla kaydedin',
  }),

  id: make({ title: 'Susun percakapan AI Anda', folderLabel: '📁 Mode Folder', promptLabel: '📝 Mode Prompt',
    dev: 'Pengembangan', research: 'Riset', writing: 'Penulisan',
    ctxMenuSaveLabel: 'Simpan ke Folder AI', syncFolderName: 'Folder AI (Sync)',
    aiReply: 'Berikut versi yang telah direfaktor dengan async/await dan penanganan error yang tepat…',
    sidebarRecent: 'Terbaru',
    chatInputPlaceholder: 'Tanyakan apa saja',
    ctxBack: 'Kembali', ctxForward: 'Maju', ctxSavePage: 'Simpan halaman sebagai…', ctxPrint: 'Cetak…',
    devChat1: 'Refaktor API Node.js', devChat2: 'Debug React Hook', devChat3: 'Tulis Unit Test',
    resChat1: 'Analisis Pasar 2025', resChat2: 'Tinjauan Pesaing',
    writeChat1: 'Artikel Blog — Produktivitas AI', writeChat2: 'Draf Newsletter',
    codeReviewer: 'Tinjauan Kode', codeReviewerText: 'Tinjau kode berikut untuk bug, masalah keamanan, dan praktik terbaik. Sarankan perbaikan konkret dengan penjelasan.',
    emailPro: 'Email Pro', emailProText: 'Tulis email profesional untuk konteks berikut. Jadilah ringkas, jelas, dan gunakan nada sopan. Tandatangani dengan nama saya.',
    explainSimply: 'Jelaskan dengan Sederhana', blogOutline: 'Kerangka Blog',
    debugHelper: 'Pembantu Debug', debugHelperText: 'Saya memiliki error atau perilaku tak terduga berikut. Bantu saya mendiagnosis akar masalah langkah demi langkah, lalu sarankan perbaikan.',
    folderScreenTitle: 'Semua obrolan AI Anda, satu tempat teratur',
    promptScreenTitle: 'Prompt terbaik Anda, siap untuk AI apapun',
    mobileScreenTitle: 'Akses obrolan AI dari ponsel Anda',
    contextMenuScreenTitle: 'Simpan percakapan AI dengan satu klik kanan',
  }),

  zh_TW: make({ title: '整理您的 AI 對話', folderLabel: '📁 資料夾模式', promptLabel: '📝 提示詞模式',
    dev: '開發', research: '研究', writing: '寫作',
    ctxMenuSaveLabel: '儲存到 AI 資料夾', syncFolderName: 'AI 資料夾 (同步)',
    aiReply: '以下是使用 async/await 和適當錯誤處理的整理後版本…',
    sidebarRecent: '最近',
    chatInputPlaceholder: '問我任何問題',
    ctxBack: '返回', ctxForward: '前進', ctxSavePage: '另存網頁…', ctxPrint: '列印…',
    devChat1: '重構 Node.js API', devChat2: '除錯 React Hook', devChat3: '撰寫單元測試',
    resChat1: '2025 市場分析', resChat2: '競爭對手概覽',
    writeChat1: '部落格文章 — AI 生產力', writeChat2: '電子報草稿',
    codeReviewer: '程式碼審查', codeReviewerText: '審查以下程式碼的錯誤、安全問題和最佳實踐。請提出具體的改進建議並附上說明。',
    emailPro: '電子郵件專家', emailProText: '為以下情境撰寫一封專業電子郵件。請簡潔、清晰，並使用禮貌的語氣。以我的名字署名。',
    explainSimply: '簡單解釋', blogOutline: '部落格大綱',
    debugHelper: '除錯助手', debugHelperText: '我遇到了以下錯誤或意外行為。請逐步協助我診斷根本原因，然後建議修復方法。',
    folderScreenTitle: '所有 AI 對話，一個整齊的地方',
    promptScreenTitle: '最佳提示詞，隨時可用於任何 AI',
    mobileScreenTitle: '從手機存取您的 AI 對話',
    contextMenuScreenTitle: '右鍵一鍵儲存任意 AI 對話',
  }),

  vi: make({ title: 'Sắp xếp các cuộc trò chuyện AI', folderLabel: '📁 Chế độ thư mục', promptLabel: '📝 Chế độ prompt',
    dev: 'Lập trình', research: 'Nghiên cứu', writing: 'Viết lách',
    ctxMenuSaveLabel: 'Lưu vào Thư mục AI', syncFolderName: 'Thư mục AI (Sync)',
    aiReply: 'Đây là phiên bản đã được tái cấu trúc với async/await và xử lý lỗi phù hợp…',
    sidebarRecent: 'Gần đây',
    chatInputPlaceholder: 'Hỏi bất cứ điều gì',
    ctxBack: 'Quay lại', ctxForward: 'Tiến', ctxSavePage: 'Lưu trang dưới dạng…', ctxPrint: 'In…',
    devChat1: 'Tái cấu trúc API Node.js', devChat2: 'Debug React Hook', devChat3: 'Viết Unit Test',
    resChat1: 'Phân tích thị trường 2025', resChat2: 'Tổng quan đối thủ cạnh tranh',
    writeChat1: 'Bài viết blog — Năng suất AI', writeChat2: 'Bản nháp bản tin',
    codeReviewer: 'Xem xét code', codeReviewerText: 'Xem xét đoạn code sau để tìm lỗi, vấn đề bảo mật và các phương pháp tốt nhất. Đề xuất các cải tiến cụ thể kèm giải thích.',
    emailPro: 'Chuyên gia Email', emailProText: 'Viết một email chuyên nghiệp cho ngữ cảnh sau. Hãy ngắn gọn, rõ ràng và lịch sự. Ký tên tôi.',
    explainSimply: 'Giải thích đơn giản', blogOutline: 'Dàn ý blog',
    debugHelper: 'Trợ lý gỡ lỗi', debugHelperText: 'Tôi gặp lỗi hoặc hành vi không mong đợi sau đây. Hãy giúp tôi chẩn đoán nguyên nhân gốc rễ từng bước, sau đó đề xuất cách khắc phục.',
    folderScreenTitle: 'Tất cả chats AI của bạn, một nơi ngăn nắp',
    promptScreenTitle: 'Prompt tốt nhất của bạn, sẵn sàng cho mọi AI',
    mobileScreenTitle: 'Truy cập chat AI từ điện thoại',
    contextMenuScreenTitle: 'Lưu cuộc trò chuyện AI bằng cú nhấp chuột phải',
  }),

  bn: make({ title: 'আপনার AI কথোপকথন সংগঠিত করুন', folderLabel: '📁 ফোল্ডার মোড', promptLabel: '📝 প্রম্পট মোড',
    dev: 'ডেভেলপমেন্ট', research: 'গবেষণা', writing: 'লেখালেখি',
    ctxMenuSaveLabel: 'AI ফোল্ডারে সংরক্ষণ করুন', syncFolderName: 'AI ফোল্ডার (Sync)',
    aiReply: 'এখানে async/await এবং সঠিক এরর হ্যান্ডলিং সহ রিফ্যাক্টর করা সংস্করণ রয়েছে…',
    sidebarRecent: 'সাম্প্রতিক',
    chatInputPlaceholder: 'যা খুশি জিজ্ঞেস করুন',
    ctxBack: 'পিছনে', ctxForward: 'সামনে', ctxSavePage: 'পৃষ্ঠাটি সংরক্ষণ করুন…', ctxPrint: 'প্রিন্ট করুন…',
    devChat1: 'Node.js API রিফ্যাক্টর', devChat2: 'React Hook ডিবাগ', devChat3: 'Unit Test লেখা',
    resChat1: '২০২৫ বাজার বিশ্লেষণ', resChat2: 'প্রতিযোগী পর্যালোচনা',
    writeChat1: 'ব্লগ পোস্ট — AI উৎপাদনশীলতা', writeChat2: 'নিউজলেটার খসড়া',
    codeReviewer: 'কোড রিভিউ', codeReviewerText: 'নিম্নলিখিত কোডটি বাগ, নিরাপত্তা সমস্যা এবং সেরা পদ্ধতির জন্য পর্যালোচনা করুন। ব্যাখ্যাসহ নির্দিষ্ট উন্নতির পরামর্শ দিন।',
    emailPro: 'ইমেইল বিশেষজ্ঞ', emailProText: 'নিম্নলিখিত প্রসঙ্গের জন্য একটি পেশাদার ইমেইল লিখুন। সংক্ষিপ্ত, স্পষ্ট এবং বিনম্র স্বরে লিখুন। আমার নামে স্বাক্ষর করুন।',
    explainSimply: 'সহজভাবে ব্যাখ্যা করুন', blogOutline: 'ব্লগ রূপরেখা',
    debugHelper: 'ডিবাগ সহায়তা', debugHelperText: 'আমার নিম্নলিখিত ত্রুটি বা অপ্রত্যাশিত আচরণ রয়েছে। ধাপে ধাপে মূল কারণ নির্ণয় করতে সাহায্য করুন, তারপর একটি সমাধান পরামর্শ দিন।',
    folderScreenTitle: 'আপনার সমস্ত AI চ্যাট এক সুশৃঙ্খল জায়গায়',
    promptScreenTitle: 'আপনার সেরা প্রম্পট, যেকোনো AI-এর জন্য প্রস্তুত',
    mobileScreenTitle: 'ফোনে AI চ্যাট অ্যাক্সেস করুন',
    contextMenuScreenTitle: 'এক রাইট-ক্লিকে যেকোনো AI কথোপকথন সংরক্ষণ',
  }),

  nl: make({ title: 'Organiseer uw AI-gesprekken', folderLabel: '📁 Mappenmodus', promptLabel: '📝 Promptmodus',
    dev: 'Ontwikkeling', research: 'Onderzoek', writing: 'Schrijven',
    ctxMenuSaveLabel: 'Opslaan in AI-mappen', syncFolderName: 'AI-mappen (Sync)',
    aiReply: 'Hier is de gerefactorde versie met async/await en correcte foutafhandeling…',
    sidebarRecent: 'Recent',
    chatInputPlaceholder: 'Vraag maar',
    ctxBack: 'Terug', ctxForward: 'Vooruit', ctxSavePage: 'Pagina opslaan als…', ctxPrint: 'Afdrukken…',
    devChat1: 'Node.js API refactoren', devChat2: 'React Hook debuggen', devChat3: 'Unit tests schrijven',
    resChat1: 'Marktanalyse 2025', resChat2: 'Concurrentieoverzicht',
    writeChat1: 'Blogbericht — AI-productiviteit', writeChat2: 'Nieuwsbrief concept',
    codeReviewer: 'Codereviewer', codeReviewerText: 'Bekijk de volgende code op bugs, beveiligingsproblemen en best practices. Stel concrete verbeteringen voor met uitleg.',
    emailPro: 'E-mailprofessional', emailProText: 'Schrijf een professionele e-mail voor de volgende context. Wees beknopt, duidelijk en gebruik een beleefde toon. Onderteken met mijn naam.',
    explainSimply: 'Eenvoudig uitleggen', blogOutline: 'Blogopzet',
    debugHelper: 'Debug-assistent', debugHelperText: 'Ik heb de volgende fout of onverwacht gedrag. Help me de hoofdoorzaak stap voor stap te diagnosticeren en stel dan een oplossing voor.',
    folderScreenTitle: 'Al uw AI-gesprekken, één georganiseerde plek',
    promptScreenTitle: 'Uw beste prompts, klaar voor elke AI',
    mobileScreenTitle: 'Toegang tot AI-chats op uw telefoon',
    contextMenuScreenTitle: 'Sla een AI-gesprek op met één rechtsklik',
  }),

  sw: make({ title: 'Panga mazungumzo yako ya AI', folderLabel: '📁 Hali ya Folda', promptLabel: '📝 Hali ya Kidokezo',
    dev: 'Maendeleo', research: 'Utafiti', writing: 'Uandishi',
    ctxMenuSaveLabel: 'Hifadhi kwenye Folda za AI', syncFolderName: 'Folda za AI (Sync)',
    aiReply: 'Hapa kuna toleo lililoimarishwa na async/await na kushughulikia makosa ipasavyo…',
    sidebarRecent: 'Hivi Karibuni',
    chatInputPlaceholder: 'Uliza chochote',
    ctxBack: 'Rudi', ctxForward: 'Endelea', ctxSavePage: 'Hifadhi ukurasa kama…', ctxPrint: 'Chapisha…',
    devChat1: 'Rejesha API ya Node.js', devChat2: 'Debug React Hook', devChat3: 'Andika Majaribio ya Unit',
    resChat1: 'Uchambuzi wa Soko 2025', resChat2: 'Mapitio ya Washindani',
    writeChat1: 'Makala ya Blogu — Tija ya AI', writeChat2: 'Rasimu ya Jarida',
    codeReviewer: 'Mkaguzi wa Msimbo', codeReviewerText: 'Kagua msimbo ufuatao kwa hitilafu, matatizo ya usalama na mbinu bora. Pendekeza maboresho maalum na maelezo.',
    emailPro: 'Mtaalamu wa Barua Pepe', emailProText: 'Andika barua pepe ya kitaalamu kwa muktadha ufuatao. Kuwa mfupi, wazi na utumie sauti ya heshima. Saini kwa jina langu.',
    explainSimply: 'Eleza kwa Urahisi', blogOutline: 'Muhtasari wa Blogu',
    debugHelper: 'Msaidizi wa Debug', debugHelperText: 'Nina hitilafu au tabia isiyotarajiwa ifuatayo. Nisaidie kuchunguza sababu kuu hatua kwa hatua, kisha pendekeza suluhisho.',
    folderScreenTitle: 'Mazungumzo yako yote ya AI, mahali pamoja',
    promptScreenTitle: 'Vidokezo vyako bora, tayari kwa AI yoyote',
    mobileScreenTitle: 'Fikia mazungumzo ya AI kwenye simu yako',
    contextMenuScreenTitle: 'Hifadhi mazungumzo ya AI kwa kubofya kulia',
  }),

  tl: make({ title: 'Ayusin ang iyong mga pag-uusap sa AI', folderLabel: '📁 Folder Mode', promptLabel: '📝 Prompt Mode',
    dev: 'Pagbuo', research: 'Pananaliksik', writing: 'Pagsusulat',
    ctxMenuSaveLabel: 'I-save sa Mga AI Folder', syncFolderName: 'Mga AI Folder (Sync)',
    aiReply: 'Narito ang refactored na bersyon na may async/await at wastong error handling…',
    sidebarRecent: 'Kamakailang',
    chatInputPlaceholder: 'Magtanong ng kahit ano',
    ctxBack: 'Bumalik', ctxForward: 'Sulong', ctxSavePage: 'I-save ang pahina bilang…', ctxPrint: 'I-print…',
    devChat1: 'Refactor ng Node.js API', devChat2: 'Debug ng React Hook', devChat3: 'Pagsulat ng Unit Tests',
    resChat1: 'Pagsusuri ng Merkado 2025', resChat2: 'Pangkalahatang-ideya ng Kakumpitensya',
    writeChat1: 'Blog Post — AI Productivity', writeChat2: 'Draft ng Newsletter',
    codeReviewer: 'Code Reviewer', codeReviewerText: 'Suriin ang sumusunod na code para sa mga bug, isyu sa seguridad, at pinakamahusay na gawi. Magmungkahi ng mga konkretong pagpapabuti na may mga paliwanag.',
    emailPro: 'Email Pro', emailProText: 'Sumulat ng propesyonal na email para sa sumusunod na konteksto. Maging maigsi, malinaw, at gumamit ng magalang na tono. Lagdaan ng aking pangalan.',
    explainSimply: 'Ipaliwanag nang Simple', blogOutline: 'Blog Outline',
    debugHelper: 'Debug Helper', debugHelperText: 'Mayroon akong sumusunod na error o hindi inaasahang gawi. Tulungan mo akong i-diagnose ang ugat na sanhi nang hakbang-hakbang, pagkatapos ay magmungkahi ng solusyon.',
    folderScreenTitle: 'Lahat ng iyong AI chat, isang organisadong lugar',
    promptScreenTitle: 'Pinakamahusay mong prompt para sa anumang AI',
    mobileScreenTitle: 'I-access ang mga AI chat sa iyong telepono',
    contextMenuScreenTitle: 'I-save ang AI na pag-uusap sa isang right-click',
  }),

  th: make({ title: 'จัดระเบียบการสนทนา AI ของคุณ', folderLabel: '📁 โหมดโฟลเดอร์', promptLabel: '📝 โหมดพรอมต์',
    dev: 'การพัฒนา', research: 'การวิจัย', writing: 'การเขียน',
    ctxMenuSaveLabel: 'บันทึกไปยังโฟลเดอร์ AI', syncFolderName: 'โฟลเดอร์ AI (Sync)',
    aiReply: 'นี่คือเวอร์ชันที่ปรับปรุงใหม่โดยใช้ async/await และการจัดการข้อผิดพลาดที่เหมาะสม…',
    sidebarRecent: 'ล่าสุด',
    chatInputPlaceholder: 'ถามได้เลย',
    ctxBack: 'ย้อนกลับ', ctxForward: 'ไปข้างหน้า', ctxSavePage: 'บันทึกหน้าเว็บเป็น…', ctxPrint: 'พิมพ์…',
    devChat1: 'รีแฟกเตอร์ API Node.js', devChat2: 'ดีบัก React Hook', devChat3: 'เขียน Unit Test',
    resChat1: 'วิเคราะห์ตลาด 2025', resChat2: 'ภาพรวมคู่แข่ง',
    writeChat1: 'บล็อกโพสต์ — AI Productivity', writeChat2: 'ร่างจดหมายข่าว',
    codeReviewer: 'ผู้ตรวจสอบโค้ด', codeReviewerText: 'ตรวจสอบโค้ดต่อไปนี้สำหรับบัก ปัญหาด้านความปลอดภัย และแนวทางปฏิบัติที่ดีที่สุด แนะนำการปรับปรุงที่เป็นรูปธรรมพร้อมคำอธิบาย',
    emailPro: 'อีเมลมืออาชีพ', emailProText: 'เขียนอีเมลระดับมืออาชีพสำหรับบริบทต่อไปนี้ ให้กระชับ ชัดเจน และใช้น้ำเสียงที่สุภาพ ลงชื่อด้วยชื่อของฉัน',
    explainSimply: 'อธิบายง่ายๆ', blogOutline: 'โครงร่างบล็อก',
    debugHelper: 'ผู้ช่วยดีบัก', debugHelperText: 'ฉันมีข้อผิดพลาดหรือพฤติกรรมที่ไม่คาดคิดต่อไปนี้ ช่วยฉันวินิจฉัยสาเหตุหลักทีละขั้นตอน แล้วแนะนำวิธีแก้ไข',
    folderScreenTitle: 'แชท AI ทั้งหมดของคุณ ในที่เดียวที่เป็นระเบียบ',
    promptScreenTitle: 'พรอมต์ที่ดีที่สุดของคุณ พร้อมสำหรับทุก AI',
    mobileScreenTitle: 'เข้าถึงแชท AI จากโทรศัพท์ของคุณ',
    contextMenuScreenTitle: 'บันทึกการสนทนา AI ด้วยการคลิกขวาครั้งเดียว',
  }),

  hu: make({ title: 'Rendszerezze MI-beszélgetéseit', folderLabel: '📁 Mappaüzemmód', promptLabel: '📝 Promptüzemmód',
    dev: 'Fejlesztés', research: 'Kutatás', writing: 'Írás',
    ctxMenuSaveLabel: 'Mentés a MI-mappákba', syncFolderName: 'MI mappák (Sync)',
    aiReply: 'Íme az async/await és megfelelő hibakezeléssel refaktorált verzió…',
    sidebarRecent: 'Legújabb',
    chatInputPlaceholder: 'Kérdezz bármit',
    ctxBack: 'Vissza', ctxForward: 'Előre', ctxSavePage: 'Oldal mentése másként…', ctxPrint: 'Nyomtatás…',
    devChat1: 'Node.js API refaktorálása', devChat2: 'React Hook hibakeresése', devChat3: 'Egységtesztek írása',
    resChat1: 'Piacelemzés 2025', resChat2: 'Versenytárs-áttekintés',
    writeChat1: 'Blogbejegyzés — AI-termelékenység', writeChat2: 'Hírlevél-tervezet',
    codeReviewer: 'Kódátvizsgáló', codeReviewerText: 'Vizsgálja át az alábbi kódot hibák, biztonsági problémák és bevált módszerek szempontjából. Javasoljon konkrét fejlesztéseket magyarázatokkal.',
    emailPro: 'E-mail-szakértő', emailProText: 'Írjon professzionális e-mailt az alábbi kontextushoz. Legyen tömör, világos, és használjon udvarias hangnemet. Írja alá a nevemmel.',
    explainSimply: 'Egyszerű magyarázat', blogOutline: 'Blogvázlat',
    debugHelper: 'Hibakereső segítő', debugHelperText: 'Az alábbi hiba vagy váratlan viselkedés tapasztalható. Segítsen lépésről lépésre diagnosztizálni az okát, majd javasoljon megoldást.',
    folderScreenTitle: 'Minden AI-csevegésed egy helyen',
    promptScreenTitle: 'Legjobb promptjaid bármelyik AI-hoz',
    mobileScreenTitle: 'Érje el AI-csevegéseit telefonján',
    contextMenuScreenTitle: 'Mentse el a AI-beszélgetést egy jobb kattintással',
  }),

  ar: make({ title: 'نظّم محادثات AI الخاصة بك', folderLabel: '📁 وضع المجلدات', promptLabel: '📝 وضع المطالبات',
    dev: 'التطوير', research: 'البحث', writing: 'الكتابة',
    ctxMenuSaveLabel: 'حفظ في مجلدات AI', syncFolderName: 'مجلدات AI (مزامنة)',
    aiReply: 'إليك نسخة معاد هيكلتها نظيفة باستخدام async/await ومعالجة أخطاء مناسبة…',
    sidebarRecent: 'الأخيرة',
    chatInputPlaceholder: 'اسأل عن أي شيء',
    ctxBack: 'رجوع', ctxForward: 'للأمام', ctxSavePage: 'حفظ الصفحة باسم…', ctxPrint: 'طباعة…',
    devChat1: 'إعادة هيكلة Node.js API', devChat2: 'تصحيح React Hook', devChat3: 'كتابة اختبارات الوحدة',
    resChat1: 'تحليل السوق 2025', resChat2: 'نظرة عامة على المنافسين',
    writeChat1: 'مقالة مدونة — إنتاجية الذكاء الاصطناعي', writeChat2: 'مسودة النشرة الإخبارية',
    codeReviewer: 'مراجعة الكود', codeReviewerText: 'راجع الكود التالي بحثاً عن الأخطاء ومشاكل الأمان وأفضل الممارسات. اقترح تحسينات ملموسة مع شروح.',
    emailPro: 'البريد الاحترافي', emailProText: 'اكتب بريداً إلكترونياً احترافياً للسياق التالي. كن موجزاً وواضحاً واستخدم نبرة مهذبة. وقّع باسمي.',
    explainSimply: 'اشرح ببساطة', blogOutline: 'مخطط المدونة',
    debugHelper: 'مساعد التصحيح', debugHelperText: 'لدي الخطأ أو السلوك غير المتوقع التالي. ساعدني في تشخيص السبب الجذري خطوة بخطوة، ثم اقترح حلاً.',
    folderScreenTitle: 'كل محادثات الذكاء الاصطناعي في مكان واحد منظّم',
    promptScreenTitle: 'أفضل مطالباتك جاهزة لأي ذكاء اصطناعي',
    mobileScreenTitle: 'الوصول إلى محادثات AI من هاتفك',
    contextMenuScreenTitle: 'احفظ أي محادثة ذكاء اصطناعي بنقرة يمنى واحدة',
  }),

  ms: make({ title: 'Susun perbualan AI anda', folderLabel: '📁 Mod Folder', promptLabel: '📝 Mod Prompt',
    dev: 'Pembangunan', research: 'Penyelidikan', writing: 'Penulisan',
    ctxMenuSaveLabel: 'Simpan ke Folder AI', syncFolderName: 'Folder AI (Sync)',
    aiReply: 'Berikut adalah versi yang telah diubah suai dengan async/await dan pengendalian ralat yang betul…',
    sidebarRecent: 'Terkini',
    chatInputPlaceholder: 'Tanya apa sahaja',
    ctxBack: 'Kembali', ctxForward: 'Ke hadapan', ctxSavePage: 'Simpan halaman sebagai…', ctxPrint: 'Cetak…',
    devChat1: 'Ubah suai API Node.js', devChat2: 'Debug React hook', devChat3: 'Tulis ujian unit',
    resChat1: 'Analisis pasaran 2025', resChat2: 'Gambaran pesaing',
    writeChat1: 'Entri blog — produktiviti AI', writeChat2: 'Draf surat berita',
    codeReviewer: 'Penyemak kod', codeReviewerText: 'Semak kod berikut untuk pepijat, isu keselamatan dan amalan terbaik. Cadangkan penambahbaikan khusus dengan penjelasan.',
    emailPro: 'Email Pro', emailProText: 'Tulis e-mel profesional untuk konteks berikut. Jadilah ringkas, jelas dan gunakan nada sopan. Tandatangani dengan nama saya.',
    explainSimply: 'Jelaskan dengan mudah', blogOutline: 'Rangka blog',
    debugHelper: 'Pembantu debug', debugHelperText: 'Saya mempunyai ralat atau tingkah laku tidak dijangka berikut. Bantu saya mendiagnosis punca akar langkah demi langkah, kemudian cadangkan penyelesaian.',
    folderScreenTitle: 'Semua sembang AI anda, satu tempat teratur',
    promptScreenTitle: 'Prompt terbaik anda, sedia untuk mana-mana AI',
    mobileScreenTitle: 'Akses sembang AI dari telefon',
    contextMenuScreenTitle: 'Simpan perbualan AI dengan satu klik kanan',
  }),

  sl: make({ title: 'Organiziraj svoje pogovore z AI', folderLabel: '📁 Način map', promptLabel: '📝 Način pozivov',
    dev: 'Razvoj', research: 'Raziskava', writing: 'Pisanje',
    ctxMenuSaveLabel: 'Shrani v Mape AI', syncFolderName: 'Mape AI (Sync)',
    aiReply: 'Tukaj je čista predelana različica z async/await in ustreznim upravljanjem napak…',
    sidebarRecent: 'Nedavno',
    chatInputPlaceholder: 'Vprašajte kar koli',
    ctxBack: 'Nazaj', ctxForward: 'Naprej', ctxSavePage: 'Shrani stran kot…', ctxPrint: 'Natisni…',
    devChat1: 'Preureditev API-ja Node.js', devChat2: 'Odpravljanje napak React hook', devChat3: 'Pisanje testov enot',
    resChat1: 'Analiza trga 2025', resChat2: 'Pregled konkurentov',
    writeChat1: 'Objava na blogu — produktivnost AI', writeChat2: 'Osnutek glasila',
    codeReviewer: 'Pregled kode', codeReviewerText: 'Pregledaj naslednjo kodo za napake, varnostne težave in najboljše prakse. Predlagaj konkretne izboljšave z razlagami.',
    emailPro: 'E-pošta Pro', emailProText: 'Napiši profesionalno e-pošto za naslednji kontekst. Bodi jedrnat, jasen in uporabi vljuden ton. Podpiši se s svojim imenom.',
    explainSimply: 'Razloži preprosto', blogOutline: 'Struktura bloga',
    debugHelper: 'Pomočnik za odpravljanje napak', debugHelperText: 'Imam naslednjo napako ali nepričakovano vedenje. Pomagaj mi diagnosticirati temeljni vzrok korak za korakom in nato predlagaj rešitev.',
    folderScreenTitle: 'Vsi vaši AI klepeti na enem urejenem mestu',
    promptScreenTitle: 'Tvoji najboljši pozivi za katero koli AI',
    mobileScreenTitle: 'Dostopaj do AI klepetov s telefona',
    contextMenuScreenTitle: 'Shrani kateri koli AI pogovor z enim desnim klikom',
  }),

  bg: make({ title: 'Организирайте разговорите си с ИИ', folderLabel: '📁 Режим папки', promptLabel: '📝 Режим промпти',
    dev: 'Разработка', research: 'Изследване', writing: 'Писане',
    ctxMenuSaveLabel: 'Запази в ИИ папки', syncFolderName: 'ИИ папки (Sync)',
    aiReply: 'Ето чиста рефакторирана версия с async/await и правилна обработка на грешки…',
    sidebarRecent: 'Скорошни',
    chatInputPlaceholder: 'Питайте каквото искате',
    ctxBack: 'Nazad', ctxForward: 'Napred', ctxSavePage: 'Запази страницата като…', ctxPrint: 'Печат…',
    devChat1: 'Рефакториране на Node.js API', devChat2: 'Отстраняване на грешки в React hook', devChat3: 'Писане на unit тестове',
    resChat1: 'Анализ на пазара 2025', resChat2: 'Преглед на конкурентите',
    writeChat1: 'Блог пост — AI продуктивност', writeChat2: 'Проект на бюлетин',
    codeReviewer: 'Преглед на код', codeReviewerText: 'Прегледайте следния код за грешки, проблеми със сигурността и добри практики. Предложете конкретни подобрения с обяснения.',
    emailPro: 'Email Pro', emailProText: 'Напишете професионален имейл за следния контекст. Бъдете кратки, ясни и използвайте учтив тон. Подпишете с моето име.',
    explainSimply: 'Обясни просто', blogOutline: 'Структура на блог',
    debugHelper: 'Помощник за отстраняване на грешки', debugHelperText: 'Имам следната грешка или неочаквано поведение. Помогни ми да диагностицирам основната причина стъпка по стъпка и след това предложи решение.',
    folderScreenTitle: 'Всички AI разговори на едно място',
    promptScreenTitle: 'Вашите най-добри промпти за всяко AI',
    mobileScreenTitle: 'Достъп до AI чатовете от телефона',
    contextMenuScreenTitle: 'Запазете AI разговор с десен клик',
  }),

  sr: make({ title: 'Organizuj VI razgovore', folderLabel: '📁 Mod foldera', promptLabel: '📝 Mod promptova',
    dev: 'Razvoj', research: 'Istraživanje', writing: 'Pisanje',
    ctxMenuSaveLabel: 'Sačuvaj u VI fascikle', syncFolderName: 'VI fascikle (Sync)',
    aiReply: 'Evo čiste refaktorisane verzije s async/await i ispravnim upravljanjem greškama…',
    sidebarRecent: 'Nedavno',
    chatInputPlaceholder: 'Pitajte šta god želite',
    ctxBack: 'Nazad', ctxForward: 'Napred', ctxSavePage: 'Sačuvaj stranicu kao…', ctxPrint: 'Štampaj…',
    devChat1: 'Refaktorisanje Node.js API-ja', devChat2: 'Otklanjanje grešaka React hook-a', devChat3: 'Pisanje unit testova',
    resChat1: 'Analiza tržišta 2025', resChat2: 'Pregled konkurenata',
    writeChat1: 'Blog post — AI produktivnost', writeChat2: 'Nacrt biltena',
    codeReviewer: 'Pregled koda', codeReviewerText: 'Pregledaj sledeći kod za greške, bezbednosne probleme i dobre prakse. Predloži konkretna poboljšanja s objašnjenjima.',
    emailPro: 'Email Pro', emailProText: 'Napiši profesionalni imejl za sledeći kontekst. Budi kratak, jasan i koristi ljubazan ton. Potpiši se mojim imenom.',
    explainSimply: 'Objasni jednostavno', blogOutline: 'Struktura bloga',
    debugHelper: 'Pomoćnik za otklanjanje grešaka', debugHelperText: 'Imam sledeću grešku ili neočekivano ponašanje. Pomozi mi da dijagnostikujem osnovni uzrok korak po korak, a zatim predloži rešenje.',
    folderScreenTitle: 'Svi AI razgovori na jednom organizovanom mestu',
    promptScreenTitle: 'Tvoji najbolji promptovi za svaki AI',
    mobileScreenTitle: 'Pristupi AI razgovorima s telefona',
    contextMenuScreenTitle: 'Sačuvaj AI razgovor jednim desnim klikom',
  }),

  hr: make({ title: 'Organiziraj UI razgovore', folderLabel: '📁 Način mapa', promptLabel: '📝 Način upita',
    dev: 'Razvoj', research: 'Istraživanje', writing: 'Pisanje',
    ctxMenuSaveLabel: 'Spremi u UI mape', syncFolderName: 'UI mape (Sync)',
    aiReply: 'Evo čiste prerađene verzije s async/await i ispravnim upravljanjem pogreškama…',
    sidebarRecent: 'Nedavno',
    chatInputPlaceholder: 'Pitajte što god želite',
    ctxBack: 'Natrag', ctxForward: 'Naprijed', ctxSavePage: 'Spremi stranicu kao…', ctxPrint: 'Ispis…',
    devChat1: 'Preradba Node.js API-ja', devChat2: 'Otklanjanje pogrešaka React hook-a', devChat3: 'Pisanje testova jedinice',
    resChat1: 'Analiza tržišta 2025', resChat2: 'Pregled konkurencije',
    writeChat1: 'Objava na blogu — AI produktivnost', writeChat2: 'Nacrt newslettera',
    codeReviewer: 'Pregled koda', codeReviewerText: 'Pregledaj sljedeći kod za pogreške, sigurnosne probleme i dobre prakse. Predloži konkretna poboljšanja s objašnjenjima.',
    emailPro: 'Email Pro', emailProText: 'Napiši profesionalnu e-poštu za sljedeći kontekst. Budi sažet, jasan i koristi pristojan ton. Potpiši se svojim imenom.',
    explainSimply: 'Objasni jednostavno', blogOutline: 'Struktura bloga',
    debugHelper: 'Pomoćnik za otklanjanje pogrešaka', debugHelperText: 'Imam sljedeću pogrešku ili neočekivano ponašanje. Pomozi mi dijagnosticirati temeljni uzrok korak po korak, a zatim predloži rješenje.',
    folderScreenTitle: 'Svi vaši AI razgovori, jedno organizirano mjesto',
    promptScreenTitle: 'Tvoji najbolji upiti za bilo koji AI',
    mobileScreenTitle: 'Pristupaj AI razgovorima s telefona',
    contextMenuScreenTitle: 'Spremi AI razgovor jednim desnim klikom',
  }),

  et: make({ title: 'Korralda oma AI vestlused', folderLabel: '📁 Kaustade režiim', promptLabel: '📝 Prompti režiim',
    dev: 'Arendus', research: 'Uurimine', writing: 'Kirjutamine',
    ctxMenuSaveLabel: 'Salvesta AI kaustadesse', syncFolderName: 'AI kaustad (Sync)',
    aiReply: 'Siin on puhas refaktoreeritud versioon async/awaiti ja nõuetekohase vigade käsitlusega…',
    sidebarRecent: 'Hiljutised',
    chatInputPlaceholder: 'Küsige mida tahes',
    ctxBack: 'Tagasi', ctxForward: 'Edasi', ctxSavePage: 'Salvesta leht kui…', ctxPrint: 'Prindi…',
    devChat1: 'Node.js API refaktoreerimine', devChat2: 'React hooki silumine', devChat3: 'Ühiktestide kirjutamine',
    resChat1: 'Turuanalüüs 2025', resChat2: 'Konkurentide ülevaade',
    writeChat1: 'Blogi — tehisintellekti tootlikkus', writeChat2: 'Uudiskirja mustand',
    codeReviewer: 'Koodi ülevaatus', codeReviewerText: 'Vaata järgmine kood üle vigade, turvaprobleemide ja parimate tavade osas. Paku konkreetseid parendusi koos selgitustega.',
    emailPro: 'Meil Pro', emailProText: 'Kirjuta järgmise konteksti jaoks professionaalne meil. Ole lühike, selge ja kasuta viisakas tooni. Allkirjasta oma nimega.',
    explainSimply: 'Selgita lihtsalt', blogOutline: 'Blogi struktuur',
    debugHelper: 'Silumisassistent', debugHelperText: 'Mul on järgmine viga või ootamatu käitumine. Aita mul leida põhjus samm-sammult ja soovita seejärel lahendus.',
    folderScreenTitle: 'Kõik teie AI vestlused ühes korralikult',
    promptScreenTitle: 'Teie parimad promptid iga AI jaoks',
    mobileScreenTitle: 'Pääse AI vestlustele telefonist',
    contextMenuScreenTitle: 'Salvesta AI vestlus ühe paremklõpsuga',
  }),

  lt: make({ title: 'Tvarkyk savo AI pokalbius', folderLabel: '📁 Aplankų režimas', promptLabel: '📝 Promptų režimas',
    dev: 'Plėtojimas', research: 'Tyrimas', writing: 'Rašymas',
    ctxMenuSaveLabel: 'Išsaugoti AI aplankuose', syncFolderName: 'AI aplankai (Sync)',
    aiReply: 'Štai švariai refaktorinta versija su async/await ir tinkamu klaidų tvarkymu…',
    sidebarRecent: 'Neseniai',
    chatInputPlaceholder: 'Klauskite ko norite',
    ctxBack: 'Atgal', ctxForward: 'Pirmyn', ctxSavePage: 'Išsaugoti puslapį kaip…', ctxPrint: 'Spausdinti…',
    devChat1: 'Node.js API refaktoringas', devChat2: 'React hook derinimas', devChat3: 'Vienetinių testų rašymas',
    resChat1: 'Rinkos analizė 2025', resChat2: 'Konkurentų apžvalga',
    writeChat1: 'Tinklaraščio įrašas — DI produktyvumas', writeChat2: 'Naujienlaiškio juodraštis',
    codeReviewer: 'Kodo peržiūra', codeReviewerText: 'Peržiūrėk šį kodą klaidų, saugumo problemų ir geriausių praktikų atžvilgiu. Siūlyk konkrečius patobulinimus su paaiškinimais.',
    emailPro: 'El. pašto Pro', emailProText: 'Parašyk profesionalų el. laišką šiam kontekstui. Būk glaustas, aiškus ir naudok mandagų toną. Pasirašyk savo vardu.',
    explainSimply: 'Paaiškink paprastai', blogOutline: 'Tinklaraščio struktūra',
    debugHelper: 'Derinimo asistentas', debugHelperText: 'Turiu šią klaidą ar netikėtą elgesį. Padėk diagnozuoti pagrindinę priežastį žingsnis po žingsnio, tada pasiūlyk sprendimą.',
    folderScreenTitle: 'Visi AI pokalbiai vienoje sutvarkytoje vietoje',
    promptScreenTitle: 'Geriausi tavo promptai bet kuriam AI',
    mobileScreenTitle: 'Pasiek AI pokalbius iš telefono',
    contextMenuScreenTitle: 'Išsaugok AI pokalbį vienu dešiniuoju paspaudimu',
  }),

  lv: make({ title: 'Organizē savas AI sarunas', folderLabel: '📁 Mapju režīms', promptLabel: '📝 Uzvedņu režīms',
    dev: 'Izstrāde', research: 'Pētīšana', writing: 'Rakstīšana',
    ctxMenuSaveLabel: 'Saglabāt AI Mapēs', syncFolderName: 'AI mapes (Sync)',
    aiReply: 'Lūk, tīra pārstrukturēta versija ar async/await un pareizu kļūdu apstrādi…',
    sidebarRecent: 'Nesenie',
    chatInputPlaceholder: 'Jautājiet ko vēlaties',
    ctxBack: 'Atpakaļ', ctxForward: 'Uz priekšu', ctxSavePage: 'Saglabāt lapu kā…', ctxPrint: 'Drukāt…',
    devChat1: 'Node.js API pārstrukturēšana', devChat2: 'React hook atkļūdošana', devChat3: 'Vienību testu rakstīšana',
    resChat1: 'Tirgus analīze 2025', resChat2: 'Konkurentu pārskats',
    writeChat1: 'Bloga ieraksts — AI produktivitāte', writeChat2: 'Biļetena melnraksts',
    codeReviewer: 'Koda pārskatīšana', codeReviewerText: 'Pārskatiet šo kodu kļūdu, drošības problēmu un labāko prakšu ziņā. Ierosiniet konkrētus uzlabojumus ar paskaidrojumiem.',
    emailPro: 'E-pasta Pro', emailProText: 'Uzraksti profesionālu e-pastu šim kontekstam. Esi kodolīgs, skaidrs un izmanto pieklājīgu toni. Paraksti ar manu vārdu.',
    explainSimply: 'Izskaidro vienkārši', blogOutline: 'Bloga struktūra',
    debugHelper: 'Atkļūdošanas asistents', debugHelperText: 'Man ir šāda kļūda vai neparedzēta uzvedība. Palīdzi diagnosticēt pamatcēloni soli pa solim un pēc tam ierosiniet risinājumu.',
    folderScreenTitle: 'Visas jūsu AI sarunas vienā sakārtotā vietā',
    promptScreenTitle: 'Labākās uzvednes jebkuram AI',
    mobileScreenTitle: 'Piekļūsti AI sarunām no tālruņa',
    contextMenuScreenTitle: 'Saglabā AI sarunu ar vienu labo klikšķi',
  }),

  ca: make({ title: 'Organitza les teves converses de IA', folderLabel: '📁 Mode carpetes', promptLabel: '📝 Mode prompts',
    dev: 'Codi', research: 'Recerca', writing: 'Redacció',
    ctxMenuSaveLabel: 'Desa a Carpetes IA', syncFolderName: 'Carpetes IA (Sync)',
    aiReply: "Aquí tens una versió refactoritzada neta amb async/await i gestió d'errors adequada…",
    sidebarRecent: 'Recents',
    chatInputPlaceholder: 'Pregunteu el que vulgueu',
    ctxBack: 'Enrere', ctxForward: 'Endavant', ctxSavePage: 'Desa la pàgina com a…', ctxPrint: 'Imprimeix…',
    devChat1: "Refactoritzar l'API de Node.js", devChat2: 'Depurar hook de React', devChat3: 'Escriure proves unitàries',
    resChat1: 'Anàlisi de mercat 2025', resChat2: 'Panorama de la competència',
    writeChat1: 'Article de blog — IA', writeChat2: 'Esborrany de butlletí',
    codeReviewer: 'Revisió de codi', codeReviewerText: 'Revisa el codi següent per detectar errors, problemes de seguretat i bones pràctiques. Proposa millores concretes amb explicacions.',
    emailPro: 'Email Pro', emailProText: "Redacta un correu electrònic professional per al context següent. Sigues concís, clar i utilitza un to educat. Signa amb el meu nom.",
    explainSimply: 'Explica simplement', blogOutline: 'Estructura del blog',
    debugHelper: 'Assistent de depuració', debugHelperText: "Tinc el següent error o comportament inesperat. Ajuda'm a diagnosticar la causa arrel pas a pas i suggereix una solució.",
    folderScreenTitle: 'Tots els vostres xats IA, en un lloc organitzat',
    promptScreenTitle: 'Els vostres millors prompts per a qualsevol IA',
    mobileScreenTitle: 'Accediu als xats IA des del telèfon',
    contextMenuScreenTitle: 'Deseu qualsevol conversa IA amb un clic dret',
  }),

  uk: make({ title: 'Організуйте свої розмови зі ШІ', folderLabel: '📁 Режим тек', promptLabel: '📝 Режим промптів',
    dev: 'Розробка', research: 'Дослідження', writing: 'Написання',
    ctxMenuSaveLabel: 'Зберегти в Теки ШІ', syncFolderName: 'Теки ШІ (Sync)',
    aiReply: 'Ось чиста рефакторизована версія з async/await і правильною обробкою помилок…',
    sidebarRecent: 'Нещодавні',
    chatInputPlaceholder: 'Запитайте що завгодно',
    ctxBack: 'Nazad', ctxForward: 'Вперед', ctxSavePage: 'Зберегти сторінку як…', ctxPrint: 'Друк…',
    devChat1: 'Рефакторинг API Node.js', devChat2: 'Налагодження хука React', devChat3: 'Написання модульних тестів',
    resChat1: 'Аналіз ринку 2025', resChat2: 'Огляд конкурентів',
    writeChat1: 'Блог — продуктивність AI', writeChat2: 'Чернетка розсилки',
    codeReviewer: 'Перевірка коду', codeReviewerText: 'Перевірте наступний код на наявність помилок, проблем безпеки та найкращих практик. Запропонуйте конкретні покращення з поясненнями.',
    emailPro: 'Email Pro', emailProText: "Напишіть професійний лист для такого контексту. Будьте лаконічні, зрозумілі та використовуйте ввічливий тон. Підпишіть моїм ім'ям.",
    explainSimply: 'Поясни просто', blogOutline: 'Структура блогу',
    debugHelper: 'Помічник з налагодження', debugHelperText: 'У мене така помилка або неочікувана поведінка. Допоможи діагностувати першопричину крок за кроком, а потім запропонуй виправлення.',
    folderScreenTitle: 'Всі ваші AI-чати в одному місці',
    promptScreenTitle: 'Ваші найкращі промпти для будь-якого AI',
    mobileScreenTitle: 'Доступ до AI-чатів з телефону',
    contextMenuScreenTitle: 'Збережіть AI-розмову одним правим кліком',
  }),

  el: make({ title: 'Οργανώστε τις συνομιλίες σας με ΤΝ', folderLabel: '📁 Λειτουργία φακέλων', promptLabel: '📝 Λειτουργία prompt',
    dev: 'Ανάπτυξη', research: 'Έρευνα', writing: 'Συγγραφή',
    ctxMenuSaveLabel: 'Αποθήκευση στους Φακέλους ΤΝ', syncFolderName: 'Φάκελοι ΤΝ (Sync)',
    aiReply: 'Ορίστε μια καθαρή έκδοση με async/await και κατάλληλη διαχείριση σφαλμάτων…',
    sidebarRecent: 'Πρόσφατα',
    chatInputPlaceholder: 'Ρωτήστε ό,τι θέλετε',
    ctxBack: 'Πίσω', ctxForward: 'Μπροστά', ctxSavePage: 'Αποθήκευση σελίδας ως…', ctxPrint: 'Εκτύπωση…',
    devChat1: 'Αναδόμηση API Node.js', devChat2: 'Εντοπισμός σφαλμάτων React hook', devChat3: 'Γραφή μοναδιαίων δοκιμών',
    resChat1: 'Ανάλυση αγοράς 2025', resChat2: 'Επισκόπηση ανταγωνιστών',
    writeChat1: 'Άρθρο blog — AI παραγωγικότητα', writeChat2: 'Πρόχειρο ενημερωτικού δελτίου',
    codeReviewer: 'Αναθεωρητής κώδικα', codeReviewerText: 'Αναθεωρήστε τον παρακάτω κώδικα για σφάλματα, προβλήματα ασφαλείας και βέλτιστες πρακτικές. Προτείνετε συγκεκριμένες βελτιώσεις με εξηγήσεις.',
    emailPro: 'Email Pro', emailProText: 'Γράψτε ένα επαγγελματικό email για το παρακάτω πλαίσιο. Να είστε συνοπτικοί, σαφείς και να χρησιμοποιείτε ευγενικό τόνο. Υπογράψτε με το όνομά μου.',
    explainSimply: 'Εξήγησε απλά', blogOutline: 'Δομή άρθρου',
    debugHelper: 'Βοηθός εντοπισμού σφαλμάτων', debugHelperText: 'Έχω το παρακάτω σφάλμα ή απροσδόκητη συμπεριφορά. Βοήθησέ με να διαγνώσω τη βαθύτερη αιτία βήμα προς βήμα και πρότεινε μια λύση.',
    folderScreenTitle: 'Όλες οι συνομιλίες AI σε ένα οργανωμένο μέρος',
    promptScreenTitle: 'Τα καλύτερα prompt σας για κάθε AI',
    mobileScreenTitle: 'Πρόσβαση στις συνομιλίες AI από το τηλέφωνο',
    contextMenuScreenTitle: 'Αποθηκεύστε συνομιλία AI με δεξί κλικ',
  }),

  he: make({ title: 'ארגן את שיחות ה-AI שלך', folderLabel: '📁 מצב תיקיות', promptLabel: '📝 מצב פרומפטים',
    dev: 'פיתוח', research: 'מחקר', writing: 'כתיבה',
    ctxMenuSaveLabel: 'שמור בתיקיות AI', syncFolderName: 'תיקיות AI (Sync)',
    aiReply: 'הנה גרסה נקייה ומעוצבת מחדש עם async/await וטיפול שגיאות מתאים…',
    sidebarRecent: 'לאחרונה',
    chatInputPlaceholder: 'שאל כל דבר',
    ctxBack: 'אחורה', ctxForward: 'קדימה', ctxSavePage: 'שמור דף בשם…', ctxPrint: 'הדפס…',
    devChat1: 'שינוי מבנה API של Node.js', devChat2: 'ניפוי שגיאות ב-React hook', devChat3: 'כתיבת בדיקות יחידה',
    resChat1: 'ניתוח שוק 2025', resChat2: 'סקירת מתחרים',
    writeChat1: 'פוסט בלוג — פרודוקטיביות AI', writeChat2: 'טיוטת ניוזלטר',
    codeReviewer: 'בודק קוד', codeReviewerText: 'סקור את הקוד הבא לאיתור באגים, בעיות אבטחה ושיטות עבודה מומלצות. הצע שיפורים קונקרטיים עם הסברים.',
    emailPro: 'Email Pro', emailProText: 'כתוב אימייל מקצועי לקונטקסט הבא. היה תמציתי, ברור והשתמש בטון מנומס. חתום בשמי.',
    explainSimply: 'הסבר בפשטות', blogOutline: 'מבנה פוסט בלוג',
    debugHelper: 'עוזר ניפוי שגיאות', debugHelperText: 'יש לי את השגיאה או ההתנהגות הבלתי צפויה הבאה. עזור לי לאבחן את הסיבה השורשית צעד אחר צעד, ולאחר מכן הצע תיקון.',
    folderScreenTitle: 'כל שיחות ה-AI שלך, במקום אחד מאורגן',
    promptScreenTitle: 'הפרומפטים הטובים ביותר שלך לכל AI',
    mobileScreenTitle: "גש לשיחות AI מהטלפון",
    contextMenuScreenTitle: 'שמור כל שיחת AI בלחיצת עכבר ימנית אחת',
  }),

  nb: make({ title: 'Organiser AI-samtalene dine', folderLabel: '📁 Mappemodus', promptLabel: '📝 Promptmodus',
    dev: 'Utvikling', research: 'Forskning', writing: 'Skriving',
    ctxMenuSaveLabel: 'Lagre i AI-mapper', syncFolderName: 'AI-mapper (Sync)',
    aiReply: 'Her er en ren refaktorert versjon med async/await og riktig feilhåndtering…',
    sidebarRecent: 'Siste',
    chatInputPlaceholder: 'Spør om hva som helst',
    ctxBack: 'Tilbake', ctxForward: 'Frem', ctxSavePage: 'Lagre side som…', ctxPrint: 'Skriv ut…',
    devChat1: 'Refaktorer Node.js API', devChat2: 'Debug React-hook', devChat3: 'Skriv enhetstester',
    resChat1: 'Markedsanalyse 2025', resChat2: 'Konkurrentoversikt',
    writeChat1: 'Blogginnlegg — AI-produktivitet', writeChat2: 'Nyhetsbrevutkast',
    codeReviewer: 'Kodeanmelder', codeReviewerText: 'Gjennomgå følgende kode for feil, sikkerhetsproblemer og beste praksis. Foreslå konkrete forbedringer med forklaringer.',
    emailPro: 'E-post Pro', emailProText: 'Skriv en profesjonell e-post for følgende kontekst. Vær kortfattet, klar og bruk en høflig tone. Signer med mitt navn.',
    explainSimply: 'Forklar enkelt', blogOutline: 'Bloggstruktur',
    debugHelper: 'Feilsøkingsassistent', debugHelperText: 'Jeg har følgende feil eller uventet oppførsel. Hjelp meg med å diagnostisere rotårsaken steg for steg, og foreslå deretter en løsning.',
    folderScreenTitle: 'Alle AI-chattene dine, ett organisert sted',
    promptScreenTitle: 'Dine beste prompter, klar for alle AI-er',
    mobileScreenTitle: 'Få tilgang til AI-chatter fra telefonen',
    contextMenuScreenTitle: 'Lagre enhver AI-samtale med ett høyreklikk',
  }),

  sv: make({ title: 'Organisera dina AI-konversationer', folderLabel: '📁 Mappläge', promptLabel: '📝 Promptläge',
    dev: 'Utveckling', research: 'Forskning', writing: 'Skrivande',
    ctxMenuSaveLabel: 'Spara i AI-mappar', syncFolderName: 'AI-mappar (Sync)',
    aiReply: 'Här är en ren refaktorerad version med async/await och korrekt felhantering…',
    sidebarRecent: 'Senaste',
    chatInputPlaceholder: 'Fråga vad som helst',
    ctxBack: 'Bakåt', ctxForward: 'Framåt', ctxSavePage: 'Spara sida som…', ctxPrint: 'Skriv ut…',
    devChat1: 'Refaktorera Node.js API', devChat2: 'Felsök React-hook', devChat3: 'Skriv enhetstester',
    resChat1: 'Marknadsanalys 2025', resChat2: 'Konkurrentöversikt',
    writeChat1: 'Blogginlägg — AI-produktivitet', writeChat2: 'Nyhetsbrevsutkast',
    codeReviewer: 'Kodgranskare', codeReviewerText: 'Granska följande kod för buggar, säkerhetsproblem och bästa praxis. Föreslå konkreta förbättringar med förklaringar.',
    emailPro: 'E-post Pro', emailProText: 'Skriv ett professionellt e-postmeddelande för följande sammanhang. Var kortfattad, tydlig och använd en artig ton. Skriv under med mitt namn.',
    explainSimply: 'Förklara enkelt', blogOutline: 'Bloggstruktur',
    debugHelper: 'Felsökningsassistent', debugHelperText: 'Jag har följande fel eller oväntat beteende. Hjälp mig att diagnostisera grundorsaken steg för steg och föreslå sedan en lösning.',
    folderScreenTitle: 'Alla dina AI-chattar, ett organiserat ställe',
    promptScreenTitle: 'Dina bästa prompter, redo för alla AI-tjänster',
    mobileScreenTitle: 'Få tillgång till AI-chattar från telefonen',
    contextMenuScreenTitle: 'Spara en AI-konversation med ett högerklick',
  }),

  fi: make({ title: 'Järjestä AI-keskustelusi', folderLabel: '📁 Kansiotila', promptLabel: '📝 Prompttila',
    dev: 'Kehitys', research: 'Tutkimus', writing: 'Kirjoittaminen',
    ctxMenuSaveLabel: 'Tallenna AI-kansioihin', syncFolderName: 'AI-kansiot (Sync)',
    aiReply: 'Tässä on siisti refaktoroitu versio, jossa käytetään async/awaitia ja asianmukaista virheenkäsittelyä…',
    sidebarRecent: 'Viimeisimmät',
    chatInputPlaceholder: 'Kysy mitä vain',
    ctxBack: 'Takaisin', ctxForward: 'Eteenpäin', ctxSavePage: 'Tallenna sivu nimellä…', ctxPrint: 'Tulosta…',
    devChat1: 'Refaktoroi Node.js API', devChat2: 'Debugaa React-hook', devChat3: 'Kirjoita yksikkötestejä',
    resChat1: 'Markkina-analyysi 2025', resChat2: 'Kilpailija-katsaus',
    writeChat1: 'Blogikirjoitus — tekoälytuottavuus', writeChat2: 'Uutiskirjeluonnos',
    codeReviewer: 'Koodiarvioija', codeReviewerText: 'Tarkista seuraava koodi virheiden, tietoturvaongelmien ja parhaiden käytäntöjen osalta. Ehdota konkreettisia parannuksia selityksineen.',
    emailPro: 'Sähköposti Pro', emailProText: 'Kirjoita ammatillinen sähköposti seuraavaan asiayhteyteen. Ole ytimekäs, selkeä ja käytä kohteliasta sävyä. Allekirjoita nimelläni.',
    explainSimply: 'Selitä yksinkertaisesti', blogOutline: 'Blogirunko',
    debugHelper: 'Vianetsintäassistentti', debugHelperText: 'Minulla on seuraava virhe tai odottamaton toiminta. Auta minua diagnosoimaan perussyy askel askeleelta ja ehdota sitten korjausta.',
    folderScreenTitle: 'Kaikki AI-chattisi, yhdessä järjestyksessä',
    promptScreenTitle: 'Parhaat promptisi valmiina mihin tahansa AI:hin',
    mobileScreenTitle: 'Käytä AI-chatteihisi puhelimellasi',
    contextMenuScreenTitle: 'Tallenna AI-keskustelu oikealla napsautuksella',
  }),

  da: make({ title: 'Organiser dine AI-samtaler', folderLabel: '📁 Mappevisning', promptLabel: '📝 Promptvisning',
    dev: 'Udvikling', research: 'Forskning', writing: 'Skrivning',
    ctxMenuSaveLabel: 'Gem i AI-mapper', syncFolderName: 'AI-mapper (Sync)',
    aiReply: 'Her er en ren refaktoreret version med async/await og korrekt fejlhåndtering…',
    sidebarRecent: 'Seneste',
    chatInputPlaceholder: 'Spørg om hvad som helst',
    ctxBack: 'Tilbage', ctxForward: 'Frem', ctxSavePage: 'Gem side som…', ctxPrint: 'Udskriv…',
    devChat1: 'Refaktorér Node.js API', devChat2: 'Debug React hook', devChat3: 'Skriv enhedstests',
    resChat1: 'Markedsanalyse 2025', resChat2: 'Konkurrentoversigt',
    writeChat1: 'Blogindlæg — AI-produktivitet', writeChat2: 'Nyhedsbrevsudkast',
    codeReviewer: 'Kodeanmelder', codeReviewerText: 'Gennemgå følgende kode for fejl, sikkerhedsproblemer og bedste praksis. Foreslå konkrete forbedringer med forklaringer.',
    emailPro: 'E-mail Pro', emailProText: 'Skriv en professionel e-mail til følgende kontekst. Vær kortfattet, klar og brug en høflig tone. Underskriv med mit navn.',
    explainSimply: 'Forklar enkelt', blogOutline: 'Blogstruktur',
    debugHelper: 'Fejlfindingsassistent', debugHelperText: 'Jeg har følgende fejl eller uventet adfærd. Hjælp mig med at diagnosticere rodårsagen trin for trin og foreslå derefter en løsning.',
    folderScreenTitle: 'Alle dine AI-chats ét organiseret sted',
    promptScreenTitle: 'Dine bedste prompts, klar til enhver AI',
    mobileScreenTitle: 'Tilgå dine AI-chats fra telefonen',
    contextMenuScreenTitle: 'Gem en AI-samtale med ét højreklik',
  }),
};

// Fallback: use English data for locales not listed above
const LOCALE_IDS = [
  'en','fr','de','es','it','pt_BR','pt_PT','ru','pl',
  'zh_CN','ja','ko','hi','ro','sk','cs','tr','id','zh_TW',
  'vi','bn','nl','sw','tl','th','hu','ar','ms','sl','bg','sr','hr',
  'et','lt','lv','ca','uk','el','he','nb','sv','fi','da',
];

const DATA = {};
for (const id of LOCALE_IDS) {
  DATA[id] = LOCALES[id] || LOCALES.en;
}

module.exports = DATA;
