document.addEventListener('DOMContentLoaded', () => {
    const titleApp = chrome.i18n.getMessage("appTitle");
    const titleImport = chrome.i18n.getMessage("importBtn");

    document.title = `${titleImport} - ${titleApp}`;

    document.getElementById('app-title').textContent = titleApp;

    const importBtn = document.getElementById('import-action-btn');
    importBtn.textContent = titleImport;

    const fileInput = document.getElementById('file-input');
    const statusMsg = document.getElementById('status-msg');

    importBtn.addEventListener('click', () => fileInput.click());

    fileInput.addEventListener('change', (e) => {
        const file = e.target.files[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = async (event) => {
            try {
                const importedData = JSON.parse(event.target.result);
                if (typeof importedData !== 'object' || importedData === null) {
                    throw new Error("Invalid Format");
                }

                loadData({ folders: {}, pinnedFolders: [] }, (data) => {
                    let currentFolders = data.folders || {};
                    let currentPinned = data.pinnedFolders || [];

                    // --- BACKWARD COMPATIBILITY MANAGEMENT ---
                    let foldersToImport = {};
                    let pinsToImport = [];

                    if (importedData.folders) {
                        foldersToImport = importedData.folders;
                        if (Array.isArray(importedData.pinnedFolders)) {
                            pinsToImport = importedData.pinnedFolders;
                        }
                    } else {
                        foldersToImport = importedData;
                    }

                    // 1. Merge folders and conversations
                    for (const [folderName, chats] of Object.entries(foldersToImport)) {
                        if (!currentFolders[folderName]) currentFolders[folderName] = [];
                        chats.forEach(importedChat => {
                            if (importedChat.title && importedChat.url) {
                                const isDuplicate = currentFolders[folderName].some(chat => chat.url === importedChat.url);
                                if (!isDuplicate) currentFolders[folderName].push(importedChat);
                            }
                        });
                    }

                    // 2. Merge pins (without creating duplicates)
                    pinsToImport.forEach(pin => {
                        if (!currentPinned.includes(pin) && currentFolders[pin]) {
                            currentPinned.push(pin);
                        }
                    });

                    // Final save
                    saveData({ folders: currentFolders, pinnedFolders: currentPinned }, () => {
                        statusMsg.textContent = chrome.i18n.getMessage("alertImportSuccess") || "Import successful! Your data has been merged successfully.";
                        statusMsg.style.color = "green";
                        fileInput.value = ""; // Cleanup
                    });
                });

            } catch (error) {
                console.error(error);
                statusMsg.textContent = chrome.i18n.getMessage("alertImportError") || "Import error. Make sure it's a valid JSON file generated by this extension.";
                statusMsg.style.color = "red";
                fileInput.value = ""; // Cleanup
            }
        };
        reader.readAsText(file);
    });
});