document.addEventListener('DOMContentLoaded', () => {
    const titleApp = chrome.i18n.getMessage("appTitle");
    const titleImport = chrome.i18n.getMessage("importBtn");

    document.title = `${titleImport} - ${titleApp}`;

    document.getElementById('app-title').textContent = titleApp;

    const importBtn = document.getElementById('import-action-btn');
    importBtn.textContent = titleImport;

    const fileInput = document.getElementById('file-input');
    const statusMsg = document.getElementById('status-msg');

    importBtn.addEventListener('click', () => fileInput.click());

    fileInput.addEventListener('change', (e) => {
        const file = e.target.files[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = async (event) => {
            try {
                const importedData = JSON.parse(event.target.result);

                await mergeImportData(importedData);

                statusMsg.textContent = chrome.i18n.getMessage("alertImportSuccess") || "Import successful! Your data has been merged successfully.";
                statusMsg.style.color = "green";
                fileInput.value = ""; // Cleanup

            } catch (error) {
                console.error("Erreur d'importation :", error);
                statusMsg.textContent = chrome.i18n.getMessage("alertImportError") || "Import error. Make sure it's a valid JSON file generated by this extension.";
                statusMsg.style.color = "red";
                fileInput.value = ""; // Cleanup
            }
        };
        reader.readAsText(file);
    });
});